export interface Category {
    id: string;
    label: string;
    description: string;
    color: string;
    gradient: string;
}

export interface Question {
    id: string;
    categoryId: string;
    text: string;
    depth: 1 | 2 | 3; // 1 = Light, 3 = Deep
    type?: 'normal' | 'wildcard';
    intensity?: 1 | 2 | 3; // Wildcard intensity: 1 (safe), 3 (bold)
    followUps?: string[]; // Contextual follow-up questions
}

export const CATEGORIES: Category[] = [
    {
        id: "ice-breaker",
        label: "Ice Breaker",
        description: "Pemanasan dulu gais, biar nggak kaku.",
        color: "bg-blue-500",
        gradient: "from-blue-400 to-blue-600"
    },
    {
        id: "deep-talk",
        label: "Deep Talk",
        description: "Ngobrolin perasaan, mimpi, dan realita hidup.",
        color: "bg-purple-500",
        gradient: "from-purple-400 to-purple-600"
    },
    {
        id: "reflection",
        label: "Refleksi Diri",
        description: "Flashback bentar, evaluasi diri sendiri.",
        color: "bg-emerald-500",
        gradient: "from-emerald-400 to-emerald-600"
    },
    {
        id: "nostalgia",
        label: "Nostalgia",
        description: "Masa kecil, jajan SD, dan momen alay dulu.",
        color: "bg-amber-500",
        gradient: "from-amber-400 to-amber-600"
    },
    {
        id: "fun",
        label: "Fun & Random",
        description: "Halu dikit nggak ngaruh, seru-seruan aja.",
        color: "bg-pink-500",
        gradient: "from-pink-400 to-pink-600"
    },
];

export const ALL_QUESTIONS: Question[] = [
    // ============================
    // ICE BREAKER (San-tai & Lokal)
    // ============================
    { id: "ib-1", categoryId: "ice-breaker", text: "Tim Bubur Ayam: Diaduk atau Nggak Diaduk?", depth: 1, followUps: ["Alasannya apa? Jangan bilang biar estetik doang.", "Pernah coba aliran sebaliknya nggak?"] },
    { id: "ib-2", categoryId: "ice-breaker", text: "Kalau lagi nunggu ojek online lama banget, biasanya ngapain?", depth: 1 },
    { id: "ib-3", categoryId: "ice-breaker", text: "Menu sarapan andalan yang nggak pernah salah menurutmu?", depth: 1 },
    { id: "ib-4", categoryId: "ice-breaker", text: "Apa 'guilty pleasure' jajanan minimarket kamu?", depth: 1 },
    { id: "ib-5", categoryId: "ice-breaker", text: "Sebutkan satu lagu dangdut atau koplo yang diam-diam kamu hafal liriknya!", depth: 1, followUps: ["Coba nyanyiin reff-nya dikit dong!"] },
    { id: "ib-6", categoryId: "ice-breaker", text: "Kalau ke kondangan, incaran utama kamu apa?", depth: 1, followUps: ["Sate ayam, zuppa soup, atau es krim?"] },
    { id: "ib-7", categoryId: "ice-breaker", text: "Lebih suka liburan ke gunung (dingin) atau pantai (panas)?", depth: 1 },
    { id: "ib-8", categoryId: "ice-breaker", text: "Siapa artis atau selebgram Indo yang menurutmu paling 'relate' sama hidupmu?", depth: 1 },
    { id: "ib-9", categoryId: "ice-breaker", text: "Platform medsos apa yang paling sering bikin kamu lupa waktu?", depth: 1 },
    { id: "ib-10", categoryId: "ice-breaker", text: "Kalau kamu jadi youtuber, konten apa yang bakal kamu buat?", depth: 1 },
    { id: "ib-11", categoryId: "ice-breaker", text: "Apa barang paling nggak penting yang pernah kamu beli online?", depth: 1 },
    { id: "ib-12", categoryId: "ice-breaker", text: "Pernah nggak salah kirim chat di grup keluarga? Ceritain!", depth: 1 },
    { id: "ib-13", categoryId: "ice-breaker", text: "Kalau punya uang kaget 100 juta hari ini dan harus habis, buat beli apa?", depth: 1 },
    { id: "ib-14", categoryId: "ice-breaker", text: "Lebih takut ketinggalan dompet atau ketinggalan HP?", depth: 1 },
    { id: "ib-15", categoryId: "ice-breaker", text: "Apa kebiasaan aneh kamu sebelum tidur?", depth: 1 },
    { id: "ib-16", categoryId: "ice-breaker", text: "Kalau bisa ganti nama panggilan, mau dipanggil apa?", depth: 1 },
    { id: "ib-17", categoryId: "ice-breaker", text: "Tim durian: Yay atau Nay?", depth: 1 },
    { id: "ib-18", categoryId: "ice-breaker", text: "Hal apa yang paling bikin males kalau lagi nongkrong bareng teman?", depth: 1 },
    { id: "ib-19", categoryId: "ice-breaker", text: "Mie instan kuah atau goreng? Pakai telor atau polos?", depth: 1 },
    { id: "ib-20", categoryId: "ice-breaker", text: "Pernah punya pengalaman horor receh nggak? (Bukan yang serem banget)", depth: 1 },
    { id: "ib-21", categoryId: "ice-breaker", text: "Apa aplikasi HP yang paling sering kamu buka tapi sebenernya nggak penting?", depth: 1 },
    { id: "ib-22", categoryId: "ice-breaker", text: "Sebutkan satu hal yang orang lain suka banget, tapi kamu nggak paham di mana enaknya.", depth: 1, followUps: ["Contoh: Seblak, BOBA, K-Pop?"] },
    { id: "ib-23", categoryId: "ice-breaker", text: "Kalau disuruh makan satu jenis lauk nasi padang selamanya, pilih apa?", depth: 1 },
    { id: "ib-24", categoryId: "ice-breaker", text: "Tipe orang kalau balas chat: gercep (fast response) atau nunggu mood?", depth: 1 },
    { id: "ib-25", categoryId: "ice-breaker", text: "Pernah nggak pura-pura sibuk main HP biar nggak diajak ngobrol orang?", depth: 1 },
    { id: "ib-26", categoryId: "ice-breaker", text: "Apa film Indonesia favoritmu sepanjang masa?", depth: 1 },
    { id: "ib-27", categoryId: "ice-breaker", text: "Kalau lagi macet parah di jalan, biasanya ngapain biar nggak stress?", depth: 1 },
    { id: "ib-28", categoryId: "ice-breaker", text: "Sebutkan satu skill remeh yang kamu banggakan.", depth: 1 },
    { id: "ib-29", categoryId: "ice-breaker", text: "Pilih mana: nggak bisa lihat story orang atau nggak bisa post story sendiri?", depth: 1 },
    { id: "ib-30", categoryId: "ice-breaker", text: "Apa nama grup WhatsApp paling aneh yang kamu punya?", depth: 1 },
    { id: "ib-31", categoryId: "ice-breaker", text: "Hal pertama yang kamu lakuin pas bangun tidur (selain cek HP)?", depth: 1 },
    { id: "ib-32", categoryId: "ice-breaker", text: "Kalau bisa punya asisten pribadi robot, tugas utama dia apa?", depth: 1 },
    { id: "ib-33", categoryId: "ice-breaker", text: "Aroma apa yang paling bikin kamu rileks?", depth: 1, followUps: ["Hujan? Kopi? Atau bau uang baru?"] },
    { id: "ib-34", categoryId: "ice-breaker", text: "Apa keahlian masak andalanmu (walaupun cuma masak air)?", depth: 1 },
    { id: "ib-35", categoryId: "ice-breaker", text: "Pilih: Jadi sangat pintar atau sangat beruntung?", depth: 1 },
    { id: "ib-36", categoryId: "ice-breaker", text: "Kalau lagi nunggu antrian panjang, kamu tipe yang sabar atau ngomel?", depth: 1 },
    { id: "ib-37", categoryId: "ice-breaker", text: "Apa konten TikTok/Reels yang algoritma-nya sering banget muncul di HP-mu?", depth: 1 },
    { id: "ib-38", categoryId: "ice-breaker", text: "Pernah nggak ketiduran di tempat umum? Di mana?", depth: 1 },
    { id: "ib-39", categoryId: "ice-breaker", text: "Apa topping pizza yang menurutmu haram hukumnya?", depth: 1, followUps: ["Nanas yay or nay?"] },
    { id: "ib-40", categoryId: "ice-breaker", text: "Kalau hidupmu wajib punya soundtrack lagu Indonesia, lagu apa?", depth: 1 },
    { id: "ib-41", categoryId: "ice-breaker", text: "Kamu tipe orang yang mandi cepet atau konser dulu di kamar mandi?", depth: 1 },
    { id: "ib-42", categoryId: "ice-breaker", text: "Benda apa di kamarmu yang udah rusak tapi sayang mau dibuang?", depth: 1 },
    { id: "ib-43", categoryId: "ice-breaker", text: "Apa satu kata gaul yang sampai sekarang kamu nggak ngerti cara pakenya?", depth: 1 },
    { id: "ib-44", categoryId: "ice-breaker", text: "Kalau bisa teleportasi cuma buat beli makan siang, mau makan di mana?", depth: 1 },
    { id: "ib-45", categoryId: "ice-breaker", text: "Apa emoji yang paling sering kamu pake padahal nggak sesuai mood?", depth: 1 },
    { id: "ib-46", categoryId: "ice-breaker", text: "Tim Cashless atau Tim Uang Tunai di dompet wajib tebel?", depth: 1 },
    { id: "ib-47", categoryId: "ice-breaker", text: "Apa drama kantor/kampus paling absurd yang pernah kamu denger minggu ini?", depth: 1 },
    { id: "ib-48", categoryId: "ice-breaker", text: "Kalau lagi WFC (Work From Cafe), tipe yang pesen satu minum buat 5 jam atau tau diri?", depth: 1 },
    { id: "ib-49", categoryId: "ice-breaker", text: "Sebutkan satu sticker WhatsApp yang paling sering kamu spam ke orang!", depth: 1 },
    { id: "ib-50", categoryId: "ice-breaker", text: "Pilih: Baterai HP 1% tapi bawa powerbank, atau baterai 100% tapi nggak ada sinyal?", depth: 1 },
    { id: "ib-51", categoryId: "ice-breaker", text: "Kalau makan soto/bakso, jeruk nipisnya diperes dikit atau sampai kering?", depth: 1 },
    { id: "ib-52", categoryId: "ice-breaker", text: "Kamu tim 'Silent Mode' selamanya atau 'Ring Mode' biar kedengeran?", depth: 1 },
    { id: "ib-53", categoryId: "ice-breaker", text: "Apa barang yang sering kamu pinjem ke teman tapi lupa balikin?", depth: 1, followUps: ["Korek? Pulpen? Uang parkir?"] },
    { id: "ib-54", categoryId: "ice-breaker", text: "Outfit andalan kalau lagi males mikir tapi harus keluar rumah?", depth: 1 },
    { id: "ib-55", categoryId: "ice-breaker", text: "Sebutkan satu influencer yang menurutmu kontennya 'cringe' tapi tetep kamu tonton!", depth: 1 },
    { id: "ib-56", categoryId: "ice-breaker", text: "Siapa orang terakhir yang kamu stalk di Instagram dan kenapa?", depth: 1 },
    { id: "ib-57", categoryId: "ice-breaker", text: "Apa kebiasaan anehmu sebelum tidur yang orang lain mungkin nggak lakuin?", depth: 1 },
    { id: "ib-58", categoryId: "ice-breaker", text: "Kalau kamu cuma boleh makan satu jenis makanan seumur hidup, pilih apa?", depth: 1 },
    { id: "ib-59", categoryId: "ice-breaker", text: "Menurutmu, nanas di pizza itu kriminal atau jenius?", depth: 1 },
    { id: "ib-60", categoryId: "ice-breaker", text: "Hal sepele apa yang bisa bikin mood kamu hancur seharian?", depth: 1, followUps: ["Kehujanan? Lupa bawa earphone?"] },
    { id: "ib-61", categoryId: "ice-breaker", text: "Siapa artis Indonesia yang menurutmu cocok jadi presiden?", depth: 1 },
    { id: "ib-62", categoryId: "ice-breaker", text: "Kalau punya uang kaget 100 juta harus habis dalam 1 jam, mau beli apa?", depth: 1 },
    { id: "ib-63", categoryId: "ice-breaker", text: "Apa 'Red Flag' terbesar bagimu saat baru kenal orang?", depth: 1 },
    { id: "ib-64", categoryId: "ice-breaker", text: "Kamu tim: Mandi air hangat pas udara panas, atau mandi air dingin pas udara dingin?", depth: 1 },
    { id: "ib-65", categoryId: "ice-breaker", text: "Sebutkan satu kata gaul yang kamu sering pake tapi sebenernya nggak tau artinya!", depth: 1 },
    { id: "ib-66", categoryId: "ice-breaker", text: "Kalau makan bakso, tim kuah bening original atau tim saos+kecap+sambal sampai kuah butek?", depth: 1 },
    { id: "ib-67", categoryId: "ice-breaker", text: "Apa satu barang yang selalu ada di tas kamu, tapi jarang banget kepake?", depth: 1 },
    { id: "ib-68", categoryId: "ice-breaker", text: "Martabak manis: Tim Keju atau Tim Coklat Kacang?", depth: 1, followUps: ["Kenapa? Jangan bilang karena dikasihnya itu."] },
    { id: "ib-69", categoryId: "ice-breaker", text: "Kalau lagi mandi, kamu tim pakai gayung atau shower?", depth: 1 },
    { id: "ib-70", categoryId: "ice-breaker", text: "Berapa banyak alarm yang kamu pasang buat bangun pagi? Satu cukup atau perlu lima?", depth: 1 },
    { id: "ib-71", categoryId: "ice-breaker", text: "Kulit ayam KFC: Dimakan duluan pas masih garing, atau disisain buat 'gong' terakhir?", depth: 1 },
    { id: "ib-72", categoryId: "ice-breaker", text: "Kalau kamu jadi presiden sehari, aturan konyol apa yang bakal kamu sahkan?", depth: 1 },
    { id: "ib-73", categoryId: "ice-breaker", text: "Tidur: Tim lampu mati total (gelap gulita) atau lampu nyala/remang?", depth: 1 },
    { id: "ib-74", categoryId: "ice-breaker", text: "Apa kebohongan di chat yang paling sering kamu ketik? (Contoh: 'OTW' padahal baru mandi)", depth: 1 },
    { id: "ib-75", categoryId: "ice-breaker", text: "Menurutmu, buah apa yang paling ribet cara makannya tapi worth it buat diperjuangkan?", depth: 1, followUps: ["Salak? Durian? Nangka?"] },
    { id: "ib-76", categoryId: "ice-breaker", text: "Cara pencet odol: Dari ujung bawah rapi, atau pencet tengah brutal sembarangan?", depth: 1 },
    { id: "ib-77", categoryId: "ice-breaker", text: "Kalau lagi kepepet nggak ada duit, menu hemat andalanmu apa?", depth: 1 },
    { id: "ib-78", categoryId: "ice-breaker", text: "Pernah nggak pura-pura main HP di tempat umum cuma karena canggung/nggak ada temen?", depth: 1 },
    { id: "ib-79", categoryId: "ice-breaker", text: "Apa suara yang paling bikin kamu ngilu atau merinding? (Misal: kuku di papan tulis, styrofoam)", depth: 1 },
    { id: "ib-80", categoryId: "ice-breaker", text: "Belanja baju: Tim Online (murah tapi gambling ukuran) atau Tim Offline (bisa coba tapi capek)?", depth: 1 },
    { id: "ib-81", categoryId: "ice-breaker", text: "Kalau kamu punya asisten pribadi seumur hidup, satu tugas rumah apa yang bakal kamu serahkan ke dia sepenuhnya?", depth: 1, followUps: ["Nyuci piring? Setrika? Lipat baju?"] },
    { id: "ib-82", categoryId: "ice-breaker", text: "Sebutkan satu 'Life Hack' bodoh yang ternyata sering kamu pake dan manjur!", depth: 1 },
    { id: "ib-83", categoryId: "ice-breaker", text: "Kalau lagi stress berat, makanan atau minuman apa yang paling kamu cari?", depth: 1 },
    { id: "ib-84", categoryId: "ice-breaker", text: "Tipe story Instagram teman yang kayak gimana yang paling sering kamu skip/mute?", depth: 1 },
    { id: "ib-85", categoryId: "ice-breaker", text: "Posisi tidur andalanmu gimana? Telentang, tengkurap, atau meringkuk kayak udang?", depth: 1 },
    { id: "ib-86", categoryId: "ice-breaker", text: "Apa nama panggilan masa kecilmu yang paling bikin malu kalau dipanggil di depan teman kantor/kuliah?", depth: 1 },
    { id: "ib-87", categoryId: "ice-breaker", text: "Kalau besok libur mendadak dan kamu bebas ngapain aja, hal pertama yang terlintas mau dilakuin apa?", depth: 1 },
    { id: "ib-88", categoryId: "ice-breaker", text: "Sebutkan satu lagu 'guilty pleasure' yang kamu malu ngaku kalau suka, tapi di playlist sering diputer!", depth: 1 },
    { id: "ib-89", categoryId: "ice-breaker", text: "Nonton bioskop: Tim ngunyah popcorn dari trailer, atau tim sabar nunggu film mulai?", depth: 1 },
    { id: "ib-90", categoryId: "ice-breaker", text: "Apa hal remeh yang sering bikin kamu panik setengah mati? (Contoh: Lupa matiin kompor, pegang saku nggak ada HP)", depth: 1 },

    // ============================
    // DEEP TALK (Hati ke Hati)
    // ============================
    { id: "dt-1", categoryId: "deep-talk", text: "Apa ketakutan terbesar kamu soal masa depan?", depth: 3, followUps: ["Apakah ketakutan itu realistik?", "Gimana caramu berdamai sama hal itu?"] },
    { id: "dt-2", categoryId: "deep-talk", text: "Menurutmu, apa arti 'rumah' yang sebenarnya? Bukan sekadar bangunan.", depth: 3 },
    { id: "dt-3", categoryId: "deep-talk", text: "Apa pengorbanan terbesar orang tua yang baru kamu sadari setelah dewasa?", depth: 3 },
    { id: "dt-4", categoryId: "deep-talk", text: "Kalau bisa minta maaf ke satu orang di masa lalu, kamu mau bilang apa?", depth: 3 },
    { id: "dt-5", categoryId: "deep-talk", text: "Kapan terakhir kali kamu merasa benar-benar dicintai?", depth: 3 },
    { id: "dt-6", categoryId: "deep-talk", text: "Hal apa yang selama ini kamu tahan-tahan demi menjaga perasaan orang lain?", depth: 3 },
    { id: "dt-7", categoryId: "deep-talk", text: "Apa mimpi kamu yang terpaksa dikubur karena realita?", depth: 3, followUps: ["Masih ada kesempatan buat wujudin nggak?", "Atau udah ikhlas?"] },
    { id: "dt-8", categoryId: "deep-talk", text: "Kalau pasanganmu selingkuh, ada kesempatan kedua atau langsung selesai?", depth: 3 },
    { id: "dt-9", categoryId: "deep-talk", text: "Apa nasihat tentang cinta yang menurutmu paling bullshit?", depth: 2 },
    { id: "dt-10", categoryId: "deep-talk", text: "Sifat orang tua mana yang paling kamu takutin nurun ke kamu?", depth: 3 },
    { id: "dt-11", categoryId: "deep-talk", text: "Di usia sekarang, kamu ngerasa udah jadi versi dirimu yang kamu harapkan belum?", depth: 3 },
    { id: "dt-12", categoryId: "deep-talk", text: "Apa momen terberat dalam hidupmu yang bikin kamu jadi sekuat sekarang?", depth: 3 },
    { id: "dt-13", categoryId: "deep-talk", text: "Menurutmu, uang bisa beli kebahagiaan nggak? Jujur aja.", depth: 2 },
    { id: "dt-14", categoryId: "deep-talk", text: "Apa 'red flag' dalam hubungan yang dulu kamu toleransi tapi sekarang nggak bisa lagi?", depth: 2 },
    { id: "dt-15", categoryId: "deep-talk", text: "Apa pujian yang paling berkesan yang pernah kamu terima?", depth: 2 },
    { id: "dt-16", categoryId: "deep-talk", text: "Kalau sisa hidupmu tinggal 1 tahun, apa yang bakal kamu ubah dari rutinitasmu sekarang?", depth: 3 },
    { id: "dt-17", categoryId: "deep-talk", text: "Lebih mending dicintai tapi nggak punya uang, atau kaya raya tapi kesepian?", depth: 2 },
    { id: "dt-18", categoryId: "deep-talk", text: "Apa satu rahasia yang nggak pernah kamu ceritain ke orang tua?", depth: 3 },
    { id: "dt-19", categoryId: "deep-talk", text: "Kapan terakhir kali kamu nangis sendirian? Kenapa?", depth: 3 },
    { id: "dt-20", categoryId: "deep-talk", text: "Siapa orang yang udah nggak ada di hidupmu, tapi dampaknya masih kerasa sampai sekarang?", depth: 3 },
    { id: "dt-21", categoryId: "deep-talk", text: "Definisi 'cukup' buat kamu itu kayak gimana?", depth: 3 },
    { id: "dt-22", categoryId: "deep-talk", text: "Apa penyesalan terbesar kamu di usia 20-an (atau masa remaja)?", depth: 3 },
    { id: "dt-23", categoryId: "deep-talk", text: "Kalau bisa ngulang satu hari dalam hidupmu, hari yang mana?", depth: 2 },
    { id: "dt-24", categoryId: "deep-talk", text: "Hal apa yang bikin kamu gampang ilfeel sama orang lain?", depth: 2 },
    { id: "dt-25", categoryId: "deep-talk", text: "Apa lagu yang kalau kamu dengerin, rasanya sedih banget?", depth: 2 },
    { id: "dt-26", categoryId: "deep-talk", text: "Apa ekspektasi sosial yang paling membebani kamu saat ini?", depth: 2, followUps: ["Soal nikah? Karir? Gaji?"] },
    { id: "dt-27", categoryId: "deep-talk", text: "Gimana cara kamu mengekspresikan rasa sayang ke orang terdekat? (Love language)", depth: 2 },
    { id: "dt-28", categoryId: "deep-talk", text: "Pernah nggak ngerasa sendirian padahal lagi rame-rame?", depth: 3 },
    { id: "dt-29", categoryId: "deep-talk", text: "Apa janji ke diri sendiri yang sampai sekarang belum ditepati?", depth: 3 },
    { id: "dt-30", categoryId: "deep-talk", text: "Apa legacy (warisan) ingatan yang pengen kamu tinggalin buat orang-orang di sekitarmu?", depth: 3 },
    { id: "dt-31", categoryId: "deep-talk", text: "Apa kebohongan yang kamu ucapkan ke diri sendiri biar tetap kuat?", depth: 3 },
    { id: "dt-32", categoryId: "deep-talk", text: "Kalau kamu bisa melihat masa depanmu 10 tahun lagi, apa yang paling kamu takutkan untuk dilihat?", depth: 3 },
    { id: "dt-33", categoryId: "deep-talk", text: "Siapa orang yang kamu harap masih ada di hidupmu sekarang?", depth: 3 },
    { id: "dt-34", categoryId: "deep-talk", text: "Apa momen di masa kecil yang mengubah caramu memandang dunia?", depth: 3 },
    { id: "dt-35", categoryId: "deep-talk", text: "Kapan kamu merasa paling kesepian, bahkan saat bersama orang lain?", depth: 3 },
    { id: "dt-36", categoryId: "deep-talk", text: "Apa satu hal yang ingin kamu tanyakan ke Tuhan?", depth: 3 },
    { id: "dt-37", categoryId: "deep-talk", text: "Apakah kamu merasa orang tuamu bangga dengan siapa kamu sekarang?", depth: 3 },
    { id: "dt-38", categoryId: "deep-talk", text: "Apa arti 'kumaafkan' bagimu? Apakah harus melupakan?", depth: 3 },
    { id: "dt-39", categoryId: "deep-talk", text: "Pernahkah kamu mencintai seseorang lebih dari kamu mencintai dirimu sendiri?", depth: 3, followUps: ["Apakah itu sehat?", "Menyesal nggak?"] },
    { id: "dt-40", categoryId: "deep-talk", text: "Apa kenangan terburuk tentang sekolah yang masih membekas?", depth: 2 },
    { id: "dt-41", categoryId: "deep-talk", text: "Apa impian yang kamu lepaskan demi realitas hidup?", depth: 3 },
    { id: "dt-42", categoryId: "deep-talk", text: "Jika kamu meninggal besok, apa penyesalan terbesarmu?", depth: 3 },
    { id: "dt-43", categoryId: "deep-talk", text: "Apa hal terberat yang pernah kamu lalui sendirian?", depth: 3 },
    { id: "dt-44", categoryId: "deep-talk", text: "Bagaimana kamu ingin diingat oleh teman-temanmu?", depth: 2 },
    { id: "dt-45", categoryId: "deep-talk", text: "Apa nasihat yang kamu berikan ke orang lain tapi sulit kamu lakukan sendiri?", depth: 2 },
    { id: "dt-46", categoryId: "deep-talk", text: "Apa arti kesuksesan yang sebenarnya bagimu, di luar materi?", depth: 3 },
    { id: "dt-47", categoryId: "deep-talk", text: "Kapan terakhir kali kamu merasa benar-benar hancur?", depth: 3 },
    { id: "dt-48", categoryId: "deep-talk", text: "Apa rahasia yang akan kamu bawa sampai mati?", depth: 3 },
    { id: "dt-49", categoryId: "deep-talk", text: "Siapa orang yang paling sering mengecewakanmu, tapi selalu kamu maafkan?", depth: 3 },
    { id: "dt-50", categoryId: "deep-talk", text: "Apa ketakutan terbesarmu tentang menjadi tua?", depth: 2 },
    { id: "dt-51", categoryId: "deep-talk", text: "Pernahkah kamu merasa tidak pantas mendapatkan kebahagiaan?", depth: 3 },
    { id: "dt-52", categoryId: "deep-talk", text: "Apa hal yang paling kamu rindukan dari dirimu yang dulu?", depth: 3 },
    { id: "dt-53", categoryId: "deep-talk", text: "Apa kesalahan terbesar yang pernah kamu buat dan pelajari?", depth: 3 },
    { id: "dt-54", categoryId: "deep-talk", text: "Bagaimana hubunganmu dengan ayahmu membentuk siapa kamu sekarang?", depth: 3 },
    { id: "dt-55", categoryId: "deep-talk", text: "Bagaimana hubunganmu dengan ibumu membentuk caramu mencintai?", depth: 3 },
    { id: "dt-56", categoryId: "deep-talk", text: "Apa hal yang membuatmu menangis saat menonton film?", depth: 2 },
    { id: "dt-57", categoryId: "deep-talk", text: "Apakah kamu percaya pada kesempatan kedua? Kenapa?", depth: 2 },
    { id: "dt-58", categoryId: "deep-talk", text: "Apa yang membuatmu merasa aman secara emosional?", depth: 2 },
    { id: "dt-59", categoryId: "deep-talk", text: "Pernahkah kamu menyakiti seseorang dengan sengaja? Kenapa?", depth: 3 },
    { id: "dt-60", categoryId: "deep-talk", text: "Apa hal yang paling kamu syukuri, tapi sering kamu lupa?", depth: 2 },
    { id: "dt-61", categoryId: "deep-talk", text: "Apa definisi 'cinta sejati' menurutmu?", depth: 3 },
    { id: "dt-62", categoryId: "deep-talk", text: "Apa hal yang membuatmu kehilangan rasa hormat pada seseorang?", depth: 2 },
    { id: "dt-63", categoryId: "deep-talk", text: "Jika kamu bisa menulis surat untuk dirimu di masa lalu, apa isinya?", depth: 3 },
    { id: "dt-64", categoryId: "deep-talk", text: "Apa hal yang paling sulit kamu terima tentang dirimu sendiri?", depth: 3 },
    { id: "dt-65", categoryId: "deep-talk", text: "Kapan kamu merasa paling tidak berdaya?", depth: 3 },
    { id: "dt-66", categoryId: "deep-talk", text: "Apa yang membuatmu bertahan saat masa-masa sulit?", depth: 2 },
    { id: "dt-67", categoryId: "deep-talk", text: "Apakah kamu bahagia dengan hidupmu saat ini?", depth: 3 },
    { id: "dt-68", categoryId: "deep-talk", text: "Apa hal yang ingin kamu ubah di dunia ini jika kamu bisa?", depth: 2 },
    { id: "dt-69", categoryId: "deep-talk", text: "Apa kenangan paling manis yang pernah kamu miliki?", depth: 2 },
    { id: "dt-70", categoryId: "deep-talk", text: "Siapa orang yang paling kamu percayai di dunia ini?", depth: 2 },
    { id: "dt-71", categoryId: "deep-talk", text: "Apa hal yang membuatmu merasa 'cukup'?", depth: 3 },
    { id: "dt-72", categoryId: "deep-talk", text: "Pernahkah kamu merasa kehilangan arah dalam hidup? Kapan?", depth: 3 },
    { id: "dt-73", categoryId: "deep-talk", text: "Apa yang kamu lakukan saat kamu merasa sedih?", depth: 2 },
    { id: "dt-74", categoryId: "deep-talk", text: "Apa yang membuatmu merasa dicintai?", depth: 2 },
    { id: "dt-75", categoryId: "deep-talk", text: "Apa hal yang paling kamu takuti kehilangan?", depth: 3 },
    { id: "dt-76", categoryId: "deep-talk", text: "Apa arti 'keluarga' bagimu?", depth: 3 },
    { id: "dt-77", categoryId: "deep-talk", text: "Apa hal yang paling kamu banggakan dalam hidupmu?", depth: 2 },
    { id: "dt-78", categoryId: "deep-talk", text: "Pernahkah kamu merasa dihakimi tanpa alasan? Bagaimana rasanya?", depth: 2 },
    { id: "dt-79", categoryId: "deep-talk", text: "Apa yang kamu pelajari dari patah hati terbesarmu?", depth: 3 },
    { id: "dt-80", categoryId: "deep-talk", text: "Apa hal yang membuatmu merasa terhubung dengan orang lain?", depth: 2 },
    { id: "dt-81", categoryId: "deep-talk", text: "Kapan terakhir kali kamu merasa benar-benar damai?", depth: 2 },
    { id: "dt-82", categoryId: "deep-talk", text: "Apa yang membuatmu merasa bersemangat bangun di pagi hari?", depth: 2 },
    { id: "dt-83", categoryId: "deep-talk", text: "Apa hal yang paling kamu hargai dalam sebuah persahabatan?", depth: 2 },
    { id: "dt-84", categoryId: "deep-talk", text: "Apa yang kamu lakukan untuk menjaga kesehatan mentalmu?", depth: 2 },
    { id: "dt-85", categoryId: "deep-talk", text: "Pernahkah kamu merasa iri dengan kehidupan orang lain? Kenapa?", depth: 3 },
    { id: "dt-86", categoryId: "deep-talk", text: "Apa hal yang paling kamu syukuri tentang tubuhmu?", depth: 2 },
    { id: "dt-87", categoryId: "deep-talk", text: "Apa yang membuatmu merasa 'pulang'?", depth: 3 },
    { id: "dt-88", categoryId: "deep-talk", text: "Apa hal yang ingin kamu capai sebelum usia 40 (atau 50)?", depth: 2 },
    { id: "dt-89", categoryId: "deep-talk", text: "Apa hal yang membuatmu merasa kesepian di keramaian?", depth: 3 },
    { id: "dt-90", categoryId: "deep-talk", text: "Apa yang kamu pelajari tentang dirimu tahun ini?", depth: 2 },
    { id: "dt-91", categoryId: "deep-talk", text: "Pernahkah kamu merasa 'gagal' sebagai manusia?", depth: 3 },
    { id: "dt-92", categoryId: "deep-talk", text: "Apa hal yang membuatmu merasa optimis tentang masa depan?", depth: 2 },
    { id: "dt-93", categoryId: "deep-talk", text: "Apa hal yang paling kamu rindukan dari masa kanak-kanak?", depth: 2 },
    { id: "dt-94", categoryId: "deep-talk", text: "Apa yang membuatmu merasa dihargai?", depth: 2 },
    { id: "dt-95", categoryId: "deep-talk", text: "Apa hal yang paling kamu sesali tidak kamu lakukan?", depth: 3 },
    { id: "dt-96", categoryId: "deep-talk", text: "Apa yang membuatmu merasa kuat?", depth: 2 },
    { id: "dt-97", categoryId: "deep-talk", text: "Pernahkah kamu merasa harus berpura-pura menjadi orang lain?", depth: 3 },
    { id: "dt-98", categoryId: "deep-talk", text: "Apa hal yang membuatmu merasa terluka secara mendalam?", depth: 3 },
    { id: "dt-99", categoryId: "deep-talk", text: "Apa yang kamu cari dalam sebuah hubungan romantis?", depth: 2 },
    { id: "dt-100", categoryId: "deep-talk", text: "Apa hal yang membuatmu merasa bersalah?", depth: 3 },
    { id: "dt-101", categoryId: "deep-talk", text: "Apa yang kamu lakukan ketika kamu merasa marah?", depth: 2 },
    { id: "dt-102", categoryId: "deep-talk", text: "Apa hal yang paling kamu nikmati saat sendirian?", depth: 2 },
    { id: "dt-103", categoryId: "deep-talk", text: "Apa yang membuatmu merasa terinspirasi?", depth: 2 },
    { id: "dt-104", categoryId: "deep-talk", text: "Pernahkah kamu merasa kehilangan jati diri?", depth: 3 },
    { id: "dt-105", categoryId: "deep-talk", text: "Apa satu kalimat yang ingin kamu dengar dari seseorang saat ini?", depth: 3 },
    { id: "dt-106", categoryId: "deep-talk", text: "Apakah kamu merasa menjadi 'Sandwich Generation'? Gimana rasanya?", depth: 3 },
    { id: "dt-107", categoryId: "deep-talk", text: "Apa standar kesuksesan yang dipaksakan orang lain ke kamu, tapi kamu nggak setuju?", depth: 3 },
    { id: "dt-108", categoryId: "deep-talk", text: "Mana yang lebih menyakitkan: perpisahan tanpa kata atau perpisahan dengan kata-kata kasar?", depth: 2 },
    { id: "dt-109", categoryId: "deep-talk", text: "Apakah kamu percaya kalau manusia bisa benar-benar berubah? Atau sifat dasar itu permanen?", depth: 3 },
    { id: "dt-110", categoryId: "deep-talk", text: "Apa ketakutan terbesarmu soal pernikahan yang bikin kamu ragu buat melangkah?", depth: 3 },
    { id: "dt-111", categoryId: "deep-talk", text: "Kalau kamu bisa melihat 'timer' sisa umur orang yang kamu sayang, apa yang bakal kamu lakuin beda?", depth: 3 },
    { id: "dt-112", categoryId: "deep-talk", text: "Apa trauma masa kecil yang baru kamu sadari dampaknya sekarang?", depth: 3 },
    { id: "dt-113", categoryId: "deep-talk", text: "Seberapa sering kamu merasa 'impostor syndrome' (merasa nggak pantes ada di posisimu sekarang)?", depth: 2 },
    { id: "dt-114", categoryId: "deep-talk", text: "Apa hal yang kamu korbankan demi karir, yang sekarang kamu sesali?", depth: 3 },
    { id: "dt-115", categoryId: "deep-talk", text: "Menurutmu, apakah 'cinta beda agama' itu layak diperjuangkan atau buang waktu?", depth: 3 },
    { id: "dt-116", categoryId: "deep-talk", text: "Apa kebohongan terbesar yang pernah kamu ceritakan ke orang tuamu demi kebaikan mereka?", depth: 3 },
    { id: "dt-117", categoryId: "deep-talk", text: "Momen apa yang mengubah pandanganmu tentang tuhan atau spiritualitas?", depth: 3 },
    { id: "dt-118", categoryId: "deep-talk", text: "Apakah kamu merasa hidupmu yang sekarang adalah yang kamu impikan 5 tahun lalu?", depth: 2 },
    { id: "dt-119", categoryId: "deep-talk", text: "Apa nasihat tentang cinta yang dulu kamu anggap klise tapi ternyata benar?", depth: 2 },
    { id: "dt-120", categoryId: "deep-talk", text: "Pilih: Punya karir cemerlang tapi kesepian, atau hidup sederhana tapi penuh cinta?", depth: 3 },
    { id: "dt-121", categoryId: "deep-talk", text: "Kapan terakhir kali kamu menangis, dan apa alasannya?", depth: 3 },
    { id: "dt-122", categoryId: "deep-talk", text: "Apa hal yang paling kamu sesali tidak kamu ucapkan kepada seseorang yang sudah tiada/pergi?", depth: 3 },
    { id: "dt-123", categoryId: "deep-talk", text: "Apakah menurutmu 'kesempatan kedua' itu pantas diberikan dalam perselingkuhan?", depth: 3 },
    { id: "dt-124", categoryId: "deep-talk", text: "Apa definisi 'Bahagia' menurut versimu saat ini? Bukan versi orang lain.", depth: 2 },
    { id: "dt-125", categoryId: "deep-talk", text: "Seberapa besar pengaruh masa lalu pasanganmu terhadap perasaanmu sekarang?", depth: 2 },
    { id: "dt-126", categoryId: "deep-talk", text: "Apa definisi 'rumah' buat kamu sekarang? Apakah itu sebuah tempat, atau seseorang?", depth: 3 },
    { id: "dt-127", categoryId: "deep-talk", text: "Apa hal yang tidak akan pernah kamu toleransi lagi dalam sebuah hubungan?", depth: 2 },
    { id: "dt-128", categoryId: "deep-talk", text: "Apakah kamu tipe yang 'mencintai' atau 'takut kehilangan'? Apa bedanya menurutmu?", depth: 3 },
    { id: "dt-129", categoryId: "deep-talk", text: "Ceritakan satu momen di mana kamu merasa sendirian padahal sedang ramai orang.", depth: 2 },
    { id: "dt-130", categoryId: "deep-talk", text: "Apa standar bahagia yang kamu tetapkan untuk pasanganmu, yang mungkin membebaninya?", depth: 3 },
    { id: "dt-131", categoryId: "deep-talk", text: "Kalau kamu bisa melihat masa depan hubunganmu saat ini dan tahu itu akan berakhir, apakah kamu akan tetap menjalaninya?", depth: 3 },
    { id: "dt-132", categoryId: "deep-talk", text: "Apa luka dari hubungan masa lalu yang sampai sekarang masih mempengaruhi caramu mencintai?", depth: 3 },
    { id: "dt-133", categoryId: "deep-talk", text: "Siapa orang yang pernah singgah sebentar tapi dampaknya besar banget di hidupmu?", depth: 2 },
    { id: "dt-134", categoryId: "deep-talk", text: "Apakah kamu percaya 'Right Person, Wrong Time'? Atau itu cuma alasan buat yang nggak mau berjuang?", depth: 2 },
    { id: "dt-135", categoryId: "deep-talk", text: "Apa hal paling menyakitkan yang pernah seseorang katakan padamu tentang kekuranganmu?", depth: 3 },
    { id: "dt-136", categoryId: "deep-talk", text: "Kapan momen kamu sadar kalau orang tuamu itu juga manusia biasa yang bisa salah dan rapuh?", depth: 3 },
    { id: "dt-137", categoryId: "deep-talk", text: "Apa satu hal yang ingin sekali kamu dengar dari mulut orang tuamu, tapi gengsi kamu minta?", depth: 3 },
    { id: "dt-138", categoryId: "deep-talk", text: "Sifat orang tua mana yang kamu benci, tapi pelan-pelan kamu sadari ada di dirimu juga?", depth: 3 },
    { id: "dt-139", categoryId: "deep-talk", text: "Kalau kamu punya anak nanti, kesalahan pola asuh apa yang bersumpah nggak akan kamu ulangi?", depth: 2 },
    { id: "dt-140", categoryId: "deep-talk", text: "Apa kenangan masa kecil yang kalau diingat bikin kamu pengen peluk dirimu yang dulu?", depth: 2 },
    { id: "dt-141", categoryId: "deep-talk", text: "Seberapa sering kamu berbohong bilang 'aku baik-baik aja' ke Ibu/Ayah?", depth: 2 },
    { id: "dt-142", categoryId: "deep-talk", text: "Apa beban keluarga yang kamu pikul sendirian tanpa ada yang tau?", depth: 3 },
    { id: "dt-143", categoryId: "deep-talk", text: "Kalau orang tuamu bisa memahami satu hal tentang pekerjaan/hidupmu, kamu ingin mereka paham soal apa?", depth: 2 },
    { id: "dt-144", categoryId: "deep-talk", text: "Siapa anggota keluarga yang paling asing bagimu, padahal tinggal serumah/dekat?", depth: 2 },
    { id: "dt-145", categoryId: "deep-talk", text: "Apakah kamu merasa sudah cukup berbakti? Atau rasa bersalah itu selalu ada?", depth: 3 },
    { id: "dt-146", categoryId: "deep-talk", text: "Apa mimpi yang kamu menyerah mengejarnya karena merasa kamu nggak cukup berbakat?", depth: 3 },
    { id: "dt-147", categoryId: "deep-talk", text: "Di umur berapa kamu merasa hidupmu 'stuck' dan nggak kemana-mana?", depth: 2 },
    { id: "dt-148", categoryId: "deep-talk", text: "Apakah kamu bekerja untuk hidup, atau hidup untuk bekerja? Jujur.", depth: 2 },
    { id: "dt-149", categoryId: "deep-talk", text: "Apa ketakutan finansial terbesarmu yang bikin kamu susah tidur?", depth: 3 },
    { id: "dt-150", categoryId: "deep-talk", text: "Kalau uang bukan masalah, kehidupan seperti apa yang benar-benar kamu inginkan?", depth: 1 },
    { id: "dt-151", categoryId: "deep-talk", text: "Apa kegagalan yang dulu rasanya kiamat, tapi sekarang kamu syukuri?", depth: 2 },
    { id: "dt-152", categoryId: "deep-talk", text: "Apakah kamu bangga dengan siapa dirimu hari ini di depan teman-teman lamamu?", depth: 2 },
    { id: "dt-153", categoryId: "deep-talk", text: "Apa harga termahal yang harus kamu bayar untuk kesuksesanmu saat ini?", depth: 3 },
    { id: "dt-154", categoryId: "deep-talk", text: "Menurutmu, apakah kamu orang yang 'ambisius' atau orang yang 'mudah puas'? Mana yang lebih tenang?", depth: 2 },
    { id: "dt-155", categoryId: "deep-talk", text: "Apa skill atau bakatmu yang orang lain remehkan, tapi kamu tahu itu berharga?", depth: 2 },
    { id: "dt-156", categoryId: "deep-talk", text: "Apa satu pertanyaan tentang hidup yang sampai sekarang belum kamu temukan jawabannya?", depth: 3 },
    { id: "dt-157", categoryId: "deep-talk", text: "Kalau sisa hidupmu tinggal 24 jam, siapa orang pertama yang akan kamu temui?", depth: 3 },
    { id: "dt-158", categoryId: "deep-talk", text: "Apa penyesalan terbesar yang kamu takutkan akan kamu bawa sampai mati?", depth: 3 },
    { id: "dt-159", categoryId: "deep-talk", text: "Kapan terakhir kali kamu merasa benar-benar 'hidup', bukan sekadar 'bertahan hidup'?", depth: 3 },
    { id: "dt-160", categoryId: "deep-talk", text: "Apa hal baik yang pernah kamu lakukan tapi tidak ada satu orang pun yang tahu?", depth: 2 },
    { id: "dt-161", categoryId: "deep-talk", text: "Menurutmu, apa tujuanmu dilahirkan ke dunia ini? (Kalau belum tahu, tebak saja)", depth: 3 },
    { id: "dt-162", categoryId: "deep-talk", text: "Apa yang membuatmu bertahan di saat-saat terberat dalam hidupmu?", depth: 3 },
    { id: "dt-163", categoryId: "deep-talk", text: "Kalau kamu bisa menghapus satu memori buruk dari otakmu, memori apa yang kamu pilih?", depth: 3 },
    { id: "dt-164", categoryId: "deep-talk", text: "Apa nasihat yang akan kamu berikan pada dirimu yang sedang menangis 5 tahun lalu?", depth: 3 },
    { id: "dt-165", categoryId: "deep-talk", text: "Satu kata yang ingin kamu tulis di batu nisanmu nanti?", depth: 3 },

    // ============================
    // REFLEKSI DIRI (Evaluasi & Growth)
    // ============================
    { id: "rf-1", categoryId: "reflection", text: "Apa satu kebiasaan buruk yang pengen banget kamu stop tahun ini?", depth: 2 },
    { id: "rf-2", categoryId: "reflection", text: "Kalau kamu ketemu versi dirimu yang umur 10 tahun, dia bakal bangga nggak sama kamu sekarang?", depth: 3 },
    { id: "rf-3", categoryId: "reflection", text: "Apa pencapaian kecil tahun ini yang belum sempet kamu rayain/hargai?", depth: 2 },
    { id: "rf-4", categoryId: "reflection", text: "Kapan terakhir kali kamu bilang 'makasih' ke diri sendiri?", depth: 2 },
    { id: "rf-5", categoryId: "reflection", text: "Apa bakat atau hobi yang dulu kamu suka tapi ditinggalin karena sibuk?", depth: 2 },
    { id: "rf-6", categoryId: "reflection", text: "Sifat apa dari dirimu yang sering bikin masalah sama orang lain?", depth: 3 },
    { id: "rf-7", categoryId: "reflection", text: "Apa hal yang paling bikin kamu insecure akhir-akhir ini?", depth: 3 },
    { id: "rf-8", categoryId: "reflection", text: "Menurutmu, kamu pendengar yang baik atau pembicara yang dominan?", depth: 2 },
    { id: "rf-9", categoryId: "reflection", text: "Apa pelajaran mahal yang kamu dapet dari 'kegagalan' terakhirmu?", depth: 2 },
    { id: "rf-10", categoryId: "reflection", text: "Kalau hidupmu adalah buku, judul bab saat ini apa?", depth: 2, followUps: ["Kenapa judulnya itu?"] },
    { id: "rf-11", categoryId: "reflection", text: "Siapa orang yang harusnya kamu hubungi tapi kamu tunda-tunda terus?", depth: 2 },
    { id: "rf-12", categoryId: "reflection", text: "Berapa jam sehari kamu dedikasikan buat scroll medsos? Worth it nggak?", depth: 2 },
    { id: "rf-13", categoryId: "reflection", text: "Apa definisi 'Bahagia' versi kamu sekarang vs 5 tahun lalu?", depth: 2 },
    { id: "rf-14", categoryId: "reflection", text: "Apakah lingkungan pertemananmu sekarang bikin kamu berkembang atau stagnan?", depth: 3 },
    { id: "rf-15", categoryId: "reflection", text: "Apa satu hal yang orang lain sering salah paham soal kamu?", depth: 2 },
    { id: "rf-16", categoryId: "reflection", text: "Apa batasan (boundary) yang perlu kamu tegesin ke orang lain?", depth: 2 },
    { id: "rf-17", categoryId: "reflection", text: "Kalau nggak ada masalah uang, kerjaan apa yang sebenernya pengen kamu lakuin?", depth: 2 },
    { id: "rf-18", categoryId: "reflection", text: "Apa momen di mana kamu merasa paling 'hidup'?", depth: 2 },
    { id: "rf-19", categoryId: "reflection", text: "Apa kritik pedas yang pernah kamu terima dan ternyata bener?", depth: 2 },
    { id: "rf-20", categoryId: "reflection", text: "Gimana caramu ngadepin stress? Sehat nggak caranya?", depth: 2 },
    { id: "rf-21", categoryId: "reflection", text: "Apa prioritas hidupmu yang sering kegeser sama hal-hal nggak penting?", depth: 2 },
    { id: "rf-22", categoryId: "reflection", text: "Kalau kamu bisa kasih satu skill baru ke dirimu secara instan, mau skill apa?", depth: 1 },
    { id: "rf-23", categoryId: "reflection", text: "Seberapa sering kamu ngebandingin diri sama orang lain di Instagram/TikTok?", depth: 2 },
    { id: "rf-24", categoryId: "reflection", text: "Apa satu hal yang kamu harap orang lain lebih apresiasi dari kamu?", depth: 2 },
    { id: "rf-25", categoryId: "reflection", text: "Apakah kamu tipe orang yang menyimpan dendam atau gampang melupakan?", depth: 2 },
    { id: "rf-26", categoryId: "reflection", text: "Apa keputusan tersulit yang pernah kamu ambil?", depth: 3 },
    { id: "rf-27", categoryId: "reflection", text: "Apa hal yang bikin kamu merasa berharga?", depth: 2 },
    { id: "rf-28", categoryId: "reflection", text: "Sudahkah kamu memaafkan dirimu atas kesalahan di masa lalu?", depth: 3 },
    { id: "rf-29", categoryId: "reflection", text: "Apa ketakutan irasional yang masih kamu percaya?", depth: 1 },
    { id: "rf-30", categoryId: "reflection", text: "Satu kata yang mendeskripsikan tahun ini buatmu?", depth: 1 },
    { id: "rf-31", categoryId: "reflection", text: "Apa hal baik yang kamu lakukan hari ini?", depth: 1 },
    { id: "rf-32", categoryId: "reflection", text: "Apa kebiasaan pagi yang membuat harimu lebih baik?", depth: 1 },
    { id: "rf-33", categoryId: "reflection", text: "Siapa orang yang paling kamu kagumi dan kenapa?", depth: 2 },
    { id: "rf-34", categoryId: "reflection", text: "Apa kegagalan yang ternyata membawamu ke arah yang lebih baik?", depth: 2 },
    { id: "rf-35", categoryId: "reflection", text: "Apa hal yang paling kamu sukai dari pekerjaanmu (atau studi)?", depth: 2 },
    { id: "rf-36", categoryId: "reflection", text: "Apa buku atau film yang mengubah cara pandangmu?", depth: 2 },
    { id: "rf-37", categoryId: "reflection", text: "Apa nasihat terbaik yang pernah kamu terima?", depth: 2 },
    { id: "rf-38", categoryId: "reflection", text: "Bagaimana cara kamu memanjakan diri sendiri?", depth: 1 },
    { id: "rf-39", categoryId: "reflection", text: "Apa keahlian yang ingin kamu pelajari tahun ini?", depth: 2 },
    { id: "rf-40", categoryId: "reflection", text: "Apa hal yang membuatmu merasa produktif?", depth: 1 },
    { id: "rf-41", categoryId: "reflection", text: "Apa tantangan terbesar yang sedang kamu hadapi?", depth: 2 },
    { id: "rf-42", categoryId: "reflection", text: "Bagaimana kamu mendefinisikan 'keseimbangan hidup'?", depth: 3 },
    { id: "rf-43", categoryId: "reflection", text: "Apa hal kecil yang bisa membuatmu tersenyum?", depth: 1 },
    { id: "rf-44", categoryId: "reflection", text: "Apa yang kamu lakukan untuk mengatasi rasa malas?", depth: 2 },
    { id: "rf-45", categoryId: "reflection", text: "Apa tujuan keuanganmu dalam 5 tahun ke depan?", depth: 2 },
    { id: "rf-46", categoryId: "reflection", text: "Apa yang membuatmu merasa percaya diri?", depth: 2 },
    { id: "rf-47", categoryId: "reflection", text: "Kapan terakhir kali kamu mencoba sesuatu yang baru?", depth: 1 },
    { id: "rf-48", categoryId: "reflection", text: "Apa hal yang paling kamu nantikan minggu ini?", depth: 1 },
    { id: "rf-49", categoryId: "reflection", text: "Bagaimana kamu menghabiskan waktu luangmu?", depth: 1 },
    { id: "rf-50", categoryId: "reflection", text: "Apa hal yang membuatmu merasa bersyukur hari ini?", depth: 1 },
    { id: "rf-51", categoryId: "reflection", text: "Apa yang kamu lakukan saat merasa bosan?", depth: 1 },
    { id: "rf-52", categoryId: "reflection", text: "Apa yang membuatmu merasa tertekan?", depth: 2 },
    { id: "rf-53", categoryId: "reflection", text: "Apa yang kamu lakukan untuk bersantai setelah hari yang panjang?", depth: 1 },
    { id: "rf-54", categoryId: "reflection", text: "Apa impian liburanmu?", depth: 1 },
    { id: "rf-55", categoryId: "reflection", text: "Apa hal yang paling kamu banggakan dari keluargamu?", depth: 2 },
    { id: "rf-56", categoryId: "reflection", text: "Apa yang membuatmu merasa dihargai di tempat kerja?", depth: 2 },
    { id: "rf-57", categoryId: "reflection", text: "Bagaimana kamu menghadapi kritik?", depth: 2 },
    { id: "rf-58", categoryId: "reflection", text: "Apa yang kamu lakukan untuk menjaga kesehatan fisikmu?", depth: 1 },
    { id: "rf-59", categoryId: "reflection", text: "Apa makanan sehat favoritmu?", depth: 1 },
    { id: "rf-60", categoryId: "reflection", text: "Apa kutipan motivasi favoritmu?", depth: 2 },
    { id: "rf-61", categoryId: "reflection", text: "Apa yang membuatmu merasa dicintai oleh pasanganmu?", depth: 2 },
    { id: "rf-62", categoryId: "reflection", text: "Apa hal yang paling kamu sukai dari dirimu secara fisik?", depth: 2 },
    { id: "rf-63", categoryId: "reflection", text: "Apa yang membuatmu merasa aman secara finansial?", depth: 2 },
    { id: "rf-64", categoryId: "reflection", text: "Apa yang kamu lakukan untuk membantu orang lain?", depth: 2 },
    { id: "rf-65", categoryId: "reflection", text: "Apa yang membuatmu merasa bangga menjadi dirimu sendiri?", depth: 3 },
    { id: "rf-66", categoryId: "reflection", text: "Apa yang kamu lakukan saat merasa cemas?", depth: 2 },
    { id: "rf-67", categoryId: "reflection", text: "Apa yang membuatmu merasa terhubung dengan alam?", depth: 2 },
    { id: "rf-68", categoryId: "reflection", text: "Apa kenangan terbaikmu tahun lalu?", depth: 2 },
    { id: "rf-69", categoryId: "reflection", text: "Apa yang kamu lakukan untuk merayakan keberhasilanmu?", depth: 1 },
    { id: "rf-70", categoryId: "reflection", text: "Apa hal yang paling kamu sukai dari teman-temanmu?", depth: 2 },
    { id: "rf-71", categoryId: "reflection", text: "Apa yang membuatmu merasa optimis hari ini?", depth: 1 },
    { id: "rf-72", categoryId: "reflection", text: "Apa yang kamu lakukan untuk meningkatkan moodmu?", depth: 1 },
    { id: "rf-73", categoryId: "reflection", text: "Apa hal yang paling kamu hargai dari waktu sendirimu?", depth: 2 },
    { id: "rf-74", categoryId: "reflection", text: "Apa yang membuatmu merasa berenergi?", depth: 1 },
    { id: "rf-75", categoryId: "reflection", text: "Apa tujuan utamamu bulan ini?", depth: 2 },
    { id: "rf-76", categoryId: "reflection", text: "Apa yang kamu lakukan untuk menjaga fokus?", depth: 2 },
    { id: "rf-77", categoryId: "reflection", text: "Apa hal yang paling kamu sukai dari rumahmu?", depth: 1 },
    { id: "rf-78", categoryId: "reflection", text: "Apa yang membuatmu merasa nyaman dengan orang baru?", depth: 2 },
    { id: "rf-79", categoryId: "reflection", text: "Apa yang kamu lakukan saat kamu tidak tahu harus berbuat apa?", depth: 2 },
    { id: "rf-80", categoryId: "reflection", text: "Apa yang membuatmu merasa bersalah, tapi sebenarnya tidak perlu?", depth: 3 },
    { id: "rf-81", categoryId: "reflection", text: "Apa yang kamu lakukan untuk memaafkan orang lain?", depth: 3 },
    { id: "rf-82", categoryId: "reflection", text: "Apa hal yang paling kamu sukai dari kotamu?", depth: 1 },
    { id: "rf-83", categoryId: "reflection", text: "Apa yang membuatmu merasa nostalgia?", depth: 1 },
    { id: "rf-84", categoryId: "reflection", text: "Apa yang kamu lakukan untuk menjaga hubungan jarak jauh?", depth: 2 },
    { id: "rf-85", categoryId: "reflection", text: "Apa hal yang paling kamu sukai dari hewan peliharaanmu (jika ada)?", depth: 1 },
    { id: "rf-86", categoryId: "reflection", text: "Apa yang membuatmu merasa dihargai oleh atasanmu?", depth: 2 },
    { id: "rf-87", categoryId: "reflection", text: "Apa yang kamu lakukan saat kamu merasa tersesat?", depth: 3 },
    { id: "rf-88", categoryId: "reflection", text: "Apa hal yang paling kamu sukai dari akhir pekan?", depth: 1 },
    { id: "rf-89", categoryId: "reflection", text: "Apa yang membuatmu merasa berani?", depth: 2 },
    { id: "rf-90", categoryId: "reflection", text: "Apa yang kamu lakukan untuk mengatasi rasa takut gagal?", depth: 3 },
    { id: "rf-91", categoryId: "reflection", text: "Apa hal yang paling kamu sukai dari tradisi keluargamu?", depth: 2 },
    { id: "rf-92", categoryId: "reflection", text: "Apa yang membuatmu merasa terkesan dengan seseorang?", depth: 2 },
    { id: "rf-93", categoryId: "reflection", text: "Apa yang kamu lakukan untuk menjaga agar tetap rendah hati?", depth: 3 },
    { id: "rf-94", categoryId: "reflection", text: "Apa hal yang paling kamu sukai dari cuaca hari ini?", depth: 1 },
    { id: "rf-95", categoryId: "reflection", text: "Apa yang membuatmu merasa sabar?", depth: 2 },
    { id: "rf-96", categoryId: "reflection", text: "Apa yang kamu lakukan saat kamu merasa kecewa?", depth: 2 },
    { id: "rf-97", categoryId: "reflection", text: "Apa hal yang paling kamu sukai dari seni?", depth: 2 },
    { id: "rf-98", categoryId: "reflection", text: "Apa yang membuatmu merasa kreatif?", depth: 2 },
    { id: "rf-99", categoryId: "reflection", text: "Apa yang kamu lakukan untuk mengatasi rasa cemburu?", depth: 3 },
    { id: "rf-100", categoryId: "reflection", text: "Apa hal yang paling kamu sukai dari musik?", depth: 1 },
    { id: "rf-101", categoryId: "reflection", text: "Apa yang membuatmu merasa bebas?", depth: 3 },
    { id: "rf-102", categoryId: "reflection", text: "Apa yang kamu lakukan untuk menjaga integritasmu?", depth: 3 },
    { id: "rf-103", categoryId: "reflection", text: "Apa hal yang paling kamu sukai dari perjalanan hidupmu sejauh ini?", depth: 3 },
    { id: "rf-104", categoryId: "reflection", text: "Apa yang membuatmu merasa penuh harapan?", depth: 2 },
    { id: "rf-105", categoryId: "reflection", text: "Apa pertanyaan yang paling sering kamu tanyakan pada dirimu sendiri?", depth: 3 },
    { id: "rf-106", categoryId: "reflection", text: "Apa sinyal tubuh (sakit/lelah) yang sering kamu abaikan karena alasan 'tanggung'?", depth: 2 },
    { id: "rf-107", categoryId: "reflection", text: "Kalau sosmed hilang besok, seberapa besar pengaruhnya ke rasa percaya dirimu?", depth: 2 },
    { id: "rf-108", categoryId: "reflection", text: "Apakah kamu tipe 'People Pleaser'? Kapan terakhir kali kamu berani bilang 'Nggak'?", depth: 2 },
    { id: "rf-109", categoryId: "reflection", text: "Apa satu 'skill' kehidupan (bukan kerjaan) yang kamu rasa kamu payah banget?", depth: 1, followUps: ["Mengatur duit? Masak? Beres-beres?"] },
    { id: "rf-110", categoryId: "reflection", text: "Berapa persen gaji yang kamu habiskan buat 'Self Reward' berkedok impulsif?", depth: 2 },
    { id: "rf-111", categoryId: "reflection", text: "Siapa orang yang paling sering menyedot energimu (energy vampire) akhir-akhir ini?", depth: 2 },
    { id: "rf-112", categoryId: "reflection", text: "Apakah kamu sudah menjadi teman yang baik buat dirimu sendiri?", depth: 3 },
    { id: "rf-113", categoryId: "reflection", text: "Apa ekspektasi orang tua yang pelan-pelan mulai kamu lepaskan?", depth: 3 },
    { id: "rf-114", categoryId: "reflection", text: "Hal apa yang membuatmu merasa 'tertinggal' dari teman-teman seumuran?", depth: 2 },
    { id: "rf-115", categoryId: "reflection", text: "Kalau tahun ini punya tema satu kata, kata apa yang kamu pilih?", depth: 1 },
    { id: "rf-116", categoryId: "reflection", text: "Apa sifat toksik dalam dirimu yang sedang berusaha kamu perbaiki?", depth: 3 },
    { id: "rf-117", categoryId: "reflection", text: "Kalau kamu bertemu versi dirimu yang berusia 10 tahun, dia bakal bangga atau kecewa?", depth: 2 },
    { id: "rf-118", categoryId: "reflection", text: "Apa pujian yang paling sulit kamu terima karena kamu merasa nggak pantas?", depth: 2 },
    { id: "rf-119", categoryId: "reflection", text: "Hal apa yang membuatmu merasa 'insecure' akhir-akhir ini?", depth: 2 },
    { id: "rf-120", categoryId: "reflection", text: "Kapan terakhir kali kamu benar-benar istirahat tanpa merasa bersalah?", depth: 2 },
    { id: "rf-121", categoryId: "reflection", text: "Apa batasan (boundary) yang baru-baru ini kamu buat untuk melindungi kesehatan mentalmu?", depth: 2 },
    { id: "rf-122", categoryId: "reflection", text: "Kalau hidupmu dijadikan buku, apa judul bab untuk fase hidupmu saat ini?", depth: 1 },
    { id: "rf-123", categoryId: "reflection", text: "Siapa orang yang paling berjasa membentuk karaktermu hari ini?", depth: 2 },
    { id: "rf-124", categoryId: "reflection", text: "Apa mimpi yang sudah kamu kubur karena merasa 'tidak realistis'?", depth: 3 },
    { id: "rf-125", categoryId: "reflection", text: "Dalam skala 1-10, seberapa jujur kamu pada diri sendiri setahun terakhir ini?", depth: 2 },

    // ============================
    // NOSTALGIA (Masa Kecil & Sekolah)
    // ============================
    { id: "ns-1", categoryId: "nostalgia", text: "Jajanan SD apa yang paling legendaris menurutmu?", depth: 1, followUps: ["Telur gulung? Lidi-lidian? Es wawan?"] },
    { id: "ns-2", categoryId: "nostalgia", text: "Kartun minggu pagi apa yang dulu wajib banget ditonton?", depth: 1 },
    { id: "ns-3", categoryId: "nostalgia", text: "Apa momen paling memalukan waktu upacara bendera?", depth: 1 },
    { id: "ns-4", categoryId: "nostalgia", text: "Dulu cita-citamu pas TK/SD mau jadi apa? Kesampaian nggak?", depth: 1 },
    { id: "ns-5", categoryId: "nostalgia", text: "Permainan tradisional apa yang dulu sering kamu mainin bareng tetangga?", depth: 1, followUps: ["Benteng? Petak umpet? Gobak sodor?"] },
    { id: "ns-6", categoryId: "nostalgia", text: "Pernah punya 'cinta monyet' pas SD/SMP? Ceritain!", depth: 1 },
    { id: "ns-7", categoryId: "nostalgia", text: "Apa lagu alay yang dulu sering kamu dengerin di warnet?", depth: 1 },
    { id: "ns-8", categoryId: "nostalgia", text: "Kapan terakhir kali kamu dapet THR lebaran (sebagai penerima)?", depth: 1 },
    { id: "ns-9", categoryId: "nostalgia", text: "Hukuman guru paling aneh yang pernah kamu dapet apa?", depth: 1 },
    { id: "ns-10", categoryId: "nostalgia", text: "Benda apa yang dulu hits banget di sekolahmu (misal: binder, tamiya, kartu yu-gi-oh)?", depth: 1 },
    { id: "ns-11", categoryId: "nostalgia", text: "Momen MOS/Ospek apa yang paling nggak bisa dilupain?", depth: 1 },
    { id: "ns-12", categoryId: "nostalgia", text: "Siapa teman sebangku yang paling 'ajaib' kelakuannya?", depth: 1 },
    { id: "ns-13", categoryId: "nostalgia", text: "Kalau bisa balik ke masa SMA selama sehari, mau ngapain?", depth: 1 },
    { id: "ns-14", categoryId: "nostalgia", text: "Buku atau komik apa yang dulu sering kamu baca diem-diem?", depth: 1 },
    { id: "ns-15", categoryId: "nostalgia", text: "Apa kenangan lebaran/liburan keluarga yang paling anget di ingatan?", depth: 2 },
    { id: "ns-16", categoryId: "nostalgia", text: "Dulu takut banget sama apa? (Misal: ondel-ondel, badut, suara tokek)", depth: 1 },
    { id: "ns-17", categoryId: "nostalgia", text: "Pernah kabur dari rumah atau bolos sekolah nggak? Gimana ceritanya?", depth: 1 },
    { id: "ns-18", categoryId: "nostalgia", text: "Siapa guru 'killer' yang sekarang malah kamu kangenin/respekin?", depth: 1 },
    { id: "ns-19", categoryId: "nostalgia", text: "Acara TV malam apa yang dulu sering ditonton bareng keluarga?", depth: 1 },
    { id: "ns-20", categoryId: "nostalgia", text: "Barang jadul apa yang sekarang pengen kamu punya lagi?", depth: 1 },
    { id: "ns-21", categoryId: "nostalgia", text: "Nick name game online atau email alay pertamamu apa?", depth: 1 },
    { id: "ns-22", categoryId: "nostalgia", text: "Dulu tim Nokia, Blackberry, atau Sony Ericsson?", depth: 1 },
    { id: "ns-23", categoryId: "nostalgia", text: "Pernah kirim surat cinta (kertas) ke siapa?", depth: 1 },
    { id: "ns-24", categoryId: "nostalgia", text: "Apa mitos masa kecil yang dulu kamu percaya banget? (Misal: nelen biji jeruk tumbuh pohon)", depth: 1 },
    { id: "ns-25", categoryId: "nostalgia", text: "Tempat nongkrong legendaris pas jaman sekolah di mana?", depth: 1 },
    { id: "ns-26", categoryId: "nostalgia", text: "Apa gaya rambut atau fashion dulu yang sekarang bikin kamu cringe?", depth: 1 },
    { id: "ns-27", categoryId: "nostalgia", text: "Siapa pahlawan fiksi masa kecilmu?", depth: 1 },
    { id: "ns-28", categoryId: "nostalgia", text: "Apa iklan TV jadul yang jingle-nya masih nempel di kepala?", depth: 1 },
    { id: "ns-29", categoryId: "nostalgia", text: "Pernah ngerasain nungguin download lagu berjam-jam?", depth: 1 },
    { id: "ns-30", categoryId: "nostalgia", text: "Hal apa yang hilang dari masa lalu dan nggak ada di zaman sekarang?", depth: 2 },
    { id: "ns-31", categoryId: "nostalgia", text: "Apa mainan yang dulu kamu pengen banget tapi nggak dibeliin?", depth: 1 },
    { id: "ns-32", categoryId: "nostalgia", text: "Siapa guru yang paling sering menghukummu?", depth: 1 },
    { id: "ns-33", categoryId: "nostalgia", text: "Apa lagu yang mengingatkanmu pada cinta monyet?", depth: 1 },
    { id: "ns-34", categoryId: "nostalgia", text: "Apa film kartun yang soundtrack-nya kamu hafal?", depth: 1 },
    { id: "ns-35", categoryId: "nostalgia", text: "Apa barang yang paling berharga bagimu saat kecil?", depth: 1 },
    { id: "ns-36", categoryId: "nostalgia", text: "Apa tempat persembunyian favoritmu saat main petak umpet?", depth: 1 },
    { id: "ns-37", categoryId: "nostalgia", text: "Apa kebohongan yang sering kamu bilang ke orang tua biar bisa main?", depth: 1 },
    { id: "ns-38", categoryId: "nostalgia", text: "Apa baju favoritmu waktu kecil?", depth: 1 },
    { id: "ns-39", categoryId: "nostalgia", text: "Siapa teman yang dulu selalu membelamu?", depth: 2 },
    { id: "ns-40", categoryId: "nostalgia", text: "Apa hadiah ulang tahun terbaik yang pernah kamu terima saat kecil?", depth: 1 },
    { id: "ns-41", categoryId: "nostalgia", text: "Apa acara TV yang dilarang orang tuamu tapi kamu tonton diam-diam?", depth: 1 },
    { id: "ns-42", categoryId: "nostalgia", text: "Apa makanan yang dulu kamu benci tapi sekarang suka?", depth: 1 },
    { id: "ns-43", categoryId: "nostalgia", text: "Apa hal bodoh yang pernah kamu lakukan karena ikut-ikutan teman?", depth: 1 },
    { id: "ns-44", categoryId: "nostalgia", text: "Apa julukanmu waktu sekolah?", depth: 1 },
    { id: "ns-45", categoryId: "nostalgia", text: "Apa permainan video game pertama yang kamu mainkan?", depth: 1 },
    { id: "ns-46", categoryId: "nostalgia", text: "Siapa artis idola masa kecilmu?", depth: 1 },
    { id: "ns-47", categoryId: "nostalgia", text: "Apa tren fashion alay yang pernah kamu ikuti?", depth: 1 },
    { id: "ns-48", categoryId: "nostalgia", text: "Apa kenangan paling lucu saat liburan sekolah?", depth: 1 },
    { id: "ns-49", categoryId: "nostalgia", text: "Apa tugas sekolah yang paling kamu benci?", depth: 1 },
    { id: "ns-50", categoryId: "nostalgia", text: "Siapa teman masa kecil yang sudah lama tidak kamu temui tapi ingin kamu hubungi?", depth: 2 },
    { id: "ns-51", categoryId: "nostalgia", text: "Apa hal yang paling kamu rindukan dari rumah nenek/kakek?", depth: 2 },
    { id: "ns-52", categoryId: "nostalgia", text: "Apa kebiasaan keluarga di masa lalu yang sekarang sudah hilang?", depth: 2 },
    { id: "ns-53", categoryId: "nostalgia", text: "Apa ketakutan masa kecil yang sekarang terasa konyol?", depth: 1 },
    { id: "ns-54", categoryId: "nostalgia", text: "Apa cita-cita teman sebangkumu dulu?", depth: 1 },
    { id: "ns-55", categoryId: "nostalgia", text: "Apa momen paling membanggakan saat sekolah dasar?", depth: 1 },
    { id: "ns-56", categoryId: "nostalgia", text: "Apa lagu yang mengingatkanmu pada perpisahan sekolah?", depth: 2 },
    { id: "ns-57", categoryId: "nostalgia", text: "Apa hal yang dulu kamu anggap keren tapi sekarang norak?", depth: 1 },
    { id: "ns-58", categoryId: "nostalgia", text: "Siapa cinta pertamamu?", depth: 2 },
    { id: "ns-59", categoryId: "nostalgia", text: "Apa momen paling menegangkan saat menyontek?", depth: 1 },
    { id: "ns-60", categoryId: "nostalgia", text: "Apa hukuman yang paling sering kamu dapatkan di rumah?", depth: 1 },
    { id: "ns-61", categoryId: "nostalgia", text: "Apa barang elektronik pertama yang kamu miliki?", depth: 1 },
    { id: "ns-62", categoryId: "nostalgia", text: "Apa situs web yang paling sering kamu buka di warnet?", depth: 1 },
    { id: "ns-63", categoryId: "nostalgia", text: "Apa gaya foto andalanmu di photobox?", depth: 1 },
    { id: "ns-64", categoryId: "nostalgia", text: "Apa koleksi barang yang pernah kamu punya?", depth: 1 },
    { id: "ns-65", categoryId: "nostalgia", text: "Apa majalah yang dulu kamu langganan?", depth: 1 },
    { id: "ns-66", categoryId: "nostalgia", text: "Apa hal yang paling kamu rindukan dari tidak adanya media sosial?", depth: 2 },
    { id: "ns-67", categoryId: "nostalgia", text: "Apa tontonan wajib saat bulan puasa?", depth: 1 },
    { id: "ns-68", categoryId: "nostalgia", text: "Apa permainan kartu yang paling sering kamu mainkan?", depth: 1 },
    { id: "ns-69", categoryId: "nostalgia", text: "Apa merek sepatu sekolah idamanmu dulu?", depth: 1 },
    { id: "ns-70", categoryId: "nostalgia", text: "Apa ekstrakurikuler yang kamu ikuti cuma buat gaya-gayaan?", depth: 1 },
    { id: "ns-71", categoryId: "nostalgia", text: "Apa momen paling berkesan saat pramuka?", depth: 1 },
    { id: "ns-72", categoryId: "nostalgia", text: "Apa film horor pertama yang kamu tonton?", depth: 1 },
    { id: "ns-73", categoryId: "nostalgia", text: "Apa lagu yang wajib ada di playlist MP3 player-mu?", depth: 1 },
    { id: "ns-74", categoryId: "nostalgia", text: "Apa operator seluler pertamamu?", depth: 1 },
    { id: "ns-75", categoryId: "nostalgia", text: "Apa isi SMS alay yang pernah kamu kirim?", depth: 1 },
    { id: "ns-76", categoryId: "nostalgia", text: "Apa nama geng mainmu dulu?", depth: 1 },
    { id: "ns-77", categoryId: "nostalgia", text: "Apa tempat wisata yang selalu dikunjungi saat study tour?", depth: 1 },
    { id: "ns-78", categoryId: "nostalgia", text: "Apa yang kamu lakukan saat mati lampu zaman dulu?", depth: 1 },
    { id: "ns-79", categoryId: "nostalgia", text: "Apa radio favoritmu dulu?", depth: 1 },
    { id: "ns-80", categoryId: "nostalgia", text: "Apa hal yang paling kamu tunggu saat 17 Agustusan?", depth: 1 },
    { id: "ns-81", categoryId: "nostalgia", text: "Apa lomba yang selalu kamu ikuti?", depth: 1 },
    { id: "ns-82", categoryId: "nostalgia", text: "Apa merek motor bebek legendaris di lingkunganmu?", depth: 1 },
    { id: "ns-83", categoryId: "nostalgia", text: "Apa jajanan yang hadiahnya paling kamu cari?", depth: 1 },
    { id: "ns-84", categoryId: "nostalgia", text: "Apa komik yang sewanya selalu antre di taman bacaan?", depth: 1 },
    { id: "ns-85", categoryId: "nostalgia", text: "Apa sinetron yang bikin kamu kesal sama tokoh antagonisnya?", depth: 1 },
    { id: "ns-86", categoryId: "nostalgia", text: "Apa yang kamu tulis di buku diary?", depth: 2 },
    { id: "ns-87", categoryId: "nostalgia", text: "Apa kenangan tentang surat sahabat pena?", depth: 1 },
    { id: "ns-88", categoryId: "nostalgia", text: "Apa yang kamu lakukan saat jam kosong di sekolah?", depth: 1 },
    { id: "ns-89", categoryId: "nostalgia", text: "Apa hal yang paling kamu ingat dari kantin sekolah?", depth: 1 },
    { id: "ns-90", categoryId: "nostalgia", text: "Apa ritual sebelum ujian nasional yang kamu lakukan?", depth: 1 },
    { id: "ns-91", categoryId: "nostalgia", text: "Apa kenangan tentang razia rambut atau HP?", depth: 1 },
    { id: "ns-92", categoryId: "nostalgia", text: "Apa yang kamu rasakan saat pertama kali naik pesawat?", depth: 1 },
    { id: "ns-93", categoryId: "nostalgia", text: "Apa kenangan tentang telepon umum koin?", depth: 1 },
    { id: "ns-94", categoryId: "nostalgia", text: "Apa yang kamu lakukan saat hujan turun waktu kecil?", depth: 1 },
    { id: "ns-95", categoryId: "nostalgia", text: "Apa lagu daerah yang diajarkan di sekolah?", depth: 1 },
    { id: "ns-96", categoryId: "nostalgia", text: "Apa kenangan tentang buku tulis sampul cokelat?", depth: 1 },
    { id: "ns-97", categoryId: "nostalgia", text: "Apa mainan yang kamu buat sendiri dari barang bekas?", depth: 1 },
    { id: "ns-98", categoryId: "nostalgia", text: "Apa kenangan tentang petasan saat lebaran?", depth: 1 },
    { id: "ns-99", categoryId: "nostalgia", text: "Apa yang kamu rasakan saat pertama kali punya pacar?", depth: 2 },
    { id: "ns-100", categoryId: "nostalgia", text: "Apa kenangan tentang sunatan atau acara adat masa kecil?", depth: 1 },
    { id: "ns-101", categoryId: "nostalgia", text: "Apa yang kamu lakukan saat liburan semester di rumah?", depth: 1 },
    { id: "ns-102", categoryId: "nostalgia", text: "Apa kenangan tentang tukang sayur atau tukang roti lewat depan rumah?", depth: 1 },
    { id: "ns-103", categoryId: "nostalgia", text: "Apa yang kamu lakukan saat nunggu buka puasa?", depth: 1 },
    { id: "ns-104", categoryId: "nostalgia", text: "Apa kenangan tentang bangun sahur?", depth: 1 },
    { id: "ns-105", categoryId: "nostalgia", text: "Apa yang paling kamu rindukan dari suasana rumah masa kecil?", depth: 2 },
    { id: "ns-106", categoryId: "nostalgia", text: "Status Facebook atau Tweet lama apa yang kalau dibaca lagi bikin pengen hapus akun?", depth: 1 },
    { id: "ns-107", categoryId: "nostalgia", text: "Apa lagu galau andalanmu zaman SMP/SMA pas lagi patah hati?", depth: 1 },
    { id: "ns-108", categoryId: "nostalgia", text: "Dulu pas jaman warnet, paket billing berapa jam yang sering kamu ambil?", depth: 1 },
    { id: "ns-109", categoryId: "nostalgia", text: "Apa merk HP impian zaman sekolah yang dulu nggak kebeli?", depth: 1, followUps: ["Nokia N-Gage? Blackberry Dakota?"] },
    { id: "ns-110", categoryId: "nostalgia", text: "Sebutkan satu sinetron atau FTV yang soundtrack-nya masih terngiang!", depth: 1 },
    { id: "ns-111", categoryId: "nostalgia", text: "Apa mainan hadiah dari Chiki/Snack yang paling kamu koleksi dulu?", depth: 1, followUps: ["Tazos? Kartu digimon?"] },
    { id: "ns-112", categoryId: "nostalgia", text: "Gaya foto apa yang wajib ada di album foto zaman alay?", depth: 1, followUps: ["Tangan di mulut? Jari telunjuk di pipi?"] },
    { id: "ns-113", categoryId: "nostalgia", text: "Siapa guru BP/BK yang paling sering berurusan sama kamu atau temanmu?", depth: 1 },
    { id: "ns-114", categoryId: "nostalgia", text: "Apa singkatan SMS alay yang dulu sering banget kamu pake?", depth: 1, followUps: ["xixixi? ea ea?"] },
    { id: "ns-115", categoryId: "nostalgia", text: "Barang couple (pasangan) apa yang pernah kamu punya sama mantan zaman sekolah?", depth: 1 },
    { id: "ns-116", categoryId: "nostalgia", text: "Dulu pas kecil, cita-citamu mau jadi apa? Kenapa sekarang berubah?", depth: 1 },
    { id: "ns-117", categoryId: "nostalgia", text: "Apa film kartun minggu pagi yang wajib banget kamu tonton dulu?", depth: 1, followUps: ["Doraemon? Digimon? Crayon Shinchan?"] },
    { id: "ns-118", categoryId: "nostalgia", text: "Sebutkan satu cheat game (GTA/The Sims) yang sampai sekarang masih hafal!", depth: 1 },
    { id: "ns-119", categoryId: "nostalgia", text: "Apa jajanan SD yang paling kotor tapi paling enak?", depth: 1, followUps: ["Telur gulung? Lidi-lidian? Es wawan?"] },
    { id: "ns-120", categoryId: "nostalgia", text: "Dulu pernah ngefans berat sama boyband/girlband apa?", depth: 1, followUps: ["Westlife? SM*SH? Cherrybelle?"] },
    { id: "ns-121", categoryId: "nostalgia", text: "Apa kenakalan di sekolah yang sampai sekarang orang tuamu nggak tau?", depth: 1 },
    { id: "ns-122", categoryId: "nostalgia", text: "Benda apa yang dulu dianggap 'orang kaya' banget kalau punya?", depth: 1, followUps: ["Sepatu roda? PS2?"] },
    { id: "ns-123", categoryId: "nostalgia", text: "Siapa teman sebangku SD/SMP yang paling kamu kangenin?", depth: 1 },
    { id: "ns-124", categoryId: "nostalgia", text: "Apa lagu yang kalau didengerin langsung bikin inget mantan pertama?", depth: 1 },
    { id: "ns-125", categoryId: "nostalgia", text: "Permainan tradisional apa yang kamu jago banget dulu?", depth: 1, followUps: ["Benteng? Galasin? Lompat tali?"] },

    // ============================
    // FUN & RANDOM (Halu & Kocak)
    // ============================
    { id: "fn-1", categoryId: "fun", text: "Kalau hidupmu dijadikan sinetron azab, judulnya kira-kira apa?", depth: 1, followUps: ["Azab apa tuh? wkwk"] },
    { id: "fn-2", categoryId: "fun", text: "Kalau kamu jadi hantu Indonesia, mau jadi apa? (Pocong/Kunti/Tuyul, dll)", depth: 1, followUps: ["Kenapa pilih itu? Biar bisa loncat-loncat?"] },
    { id: "fn-3", categoryId: "fun", text: "Skenario kiamat zombie: Senjata apa yang pertama kali kamu cari di rumah?", depth: 1 },
    { id: "fn-4", categoryId: "fun", text: "Kalau binatang bisa ngomong, binatang apa yang paling nyebelin?", depth: 1 },
    { id: "fn-5", categoryId: "fun", text: "Teori konspirasi apa yang diem-diem kamu percaya? (Misal: alien, bumi datar, dll)", depth: 1 },
    { id: "fn-6", categoryId: "fun", text: "Kalau kamu punya uang unlimited tapi cuma boleh beli barang yang huruf depannya 'K', beli apa?", depth: 1 },
    { id: "fn-7", categoryId: "fun", text: "Hal paling absurd apa yang pernah kamu lakuin pas lagi sendirian di kamar?", depth: 1 },
    { id: "fn-8", categoryId: "fun", text: "Pilih: Nggak bisa makan nasi selamanya ATAU nggak bisa akses internet selamanya?", depth: 1 },
    { id: "fn-9", categoryId: "fun", text: "Kalau kamu bisa tukeran hidup sama satu orang selama 24 jam, mau jadi siapa?", depth: 1 },
    { id: "fn-10", categoryId: "fun", text: "Apa kebohongan paling konyol yang pernah kamu bilang ke teman biar nggak jadi ketemuan?", depth: 1 },
    { id: "fn-11", categoryId: "fun", text: "Kalau alien dateng ke bumi, makanan Indonesia apa yang mau kamu suguhin biar mereka nggak jadi nyerang?", depth: 1 },
    { id: "fn-12", categoryId: "fun", text: "Sebutkan satu kata bahasa Indonesia yang kedengeran aneh kalau diulang-ulang.", depth: 1 },
    { id: "fn-13", categoryId: "fun", text: "Kalau kamu masuk penjara, kira-kira kasusnya apa?", depth: 1 },
    { id: "fn-14", categoryId: "fun", text: "Apa superpower paling nggak berguna yang kamu pengen punya?", depth: 1, followUps: ["Bisa ngubah air jadi kuah bakso?"] },
    { id: "fn-15", categoryId: "fun", text: "Siapa selebritis yang menurutmu cocok jadi presiden kita selanjutnya?", depth: 1 },
    { id: "fn-16", categoryId: "fun", text: "Pilih: Selalu salah kostum di acara penting ATAU selalu salah nyebut nama orang pas salaman?", depth: 1 },
    { id: "fn-17", categoryId: "fun", text: "Kalau kamu buka warung makan, nama warungnya apa & menu andalannya apa?", depth: 1 },
    { id: "fn-18", categoryId: "fun", text: "Apa bau aneh yang sebenernya kamu suka? (Bensin? Hujan? Ketiak sendiri?)", depth: 1 },
    { id: "fn-19", categoryId: "fun", text: "Kalau disuruh bikin sekte baru, ajaran utamanya apa?", depth: 1 },
    { id: "fn-20", categoryId: "fun", text: "Momen 'salah server' paling canggung yang pernah kamu alami?", depth: 1 },
    { id: "fn-21", categoryId: "fun", text: "Kalau hidupmu ada backsound-nya, lagu apa yang lagi muter sekarang?", depth: 1 },
    { id: "fn-22", categoryId: "fun", text: "Pilih: Tahu masa depan ATAU bisa mengubah masa lalu?", depth: 1 },
    { id: "fn-23", categoryId: "fun", text: "Siapa tokoh kartun yang sifatnya paling mirip sama kamu?", depth: 1 },
    { id: "fn-24", categoryId: "fun", text: "Apa hal ilegal yang kalau jadi legal bakal sering kamu lakuin?", depth: 1 },
    { id: "fn-25", categoryId: "fun", text: "Kalau kamu jadi influencer, kontenmu tentang apa?", depth: 1 },
    { id: "fn-26", categoryId: "fun", text: "Sebutkan 3 benda yang bakal kamu bawa kalau terdampar di pulau kosong (nggak boleh HP).", depth: 1 },
    { id: "fn-27", categoryId: "fun", text: "Kalau bisa ngilang, tempat mana yang pertama kali kamu masukin?", depth: 1 },
    { id: "fn-28", categoryId: "fun", text: "Apa nama WI-FI terkocak yang pernah kamu lihat?", depth: 1 },
    { id: "fn-29", categoryId: "fun", text: "Kalau kamu harus nikah sama makanan, makanan apa yang kamu pilih?", depth: 1 },
    { id: "fn-30", categoryId: "fun", text: "Apa chat terakhir yang kamu copy-paste?", depth: 1 },
    { id: "fn-31", categoryId: "fun", text: "Kalau kamu jadi sayuran, kamu mau jadi sayur apa dan kenapa?", depth: 1 },
    { id: "fn-32", categoryId: "fun", text: "Apa judul biografi hidupmu yang ditulis oleh orang yang membencimu?", depth: 1 },
    { id: "fn-33", categoryId: "fun", text: "Kalau kamu bisa kentut wangi, mau wangi apa?", depth: 1 },
    { id: "fn-34", categoryId: "fun", text: "Apa hal paling aneh yang pernah kamu google?", depth: 1 },
    { id: "fn-35", categoryId: "fun", text: "Kalau kamu diculik alien dan mereka minta satu alasan kenapa bumi layak diselamatkan, kamu bilang apa?", depth: 1 },
    { id: "fn-36", categoryId: "fun", text: "Apa lagu yang paling sering kamu nyanyikan di kamar mandi?", depth: 1 },
    { id: "fn-37", categoryId: "fun", text: "Kalau kamu bisa jadi benda mati selama sehari, mau jadi apa?", depth: 1 },
    { id: "fn-38", categoryId: "fun", text: "Apa kebiasaan anehmu saat makan?", depth: 1 },
    { id: "fn-39", categoryId: "fun", text: "Kalau hewan bisa bicara, hewan apa yang paling kasar?", depth: 1 },
    { id: "fn-40", categoryId: "fun", text: "Apa nama samaranmu kalau jadi mata-mata?", depth: 1 },
    { id: "fn-41", categoryId: "fun", text: "Kalau kamu punya pulau sendiri, apa aturan pertamanya?", depth: 1 },
    { id: "fn-42", categoryId: "fun", text: "Apa hal paling memalukan yang pernah kamu lakukan di depan gebetan?", depth: 1 },
    { id: "fn-43", categoryId: "fun", text: "Kalau kamu bisa menggabungkan dua hewan, hewan apa yang bakal jadi paling keren?", depth: 1 },
    { id: "fn-44", categoryId: "fun", text: "Apa hal remeh yang bisa memicu perang dunia ke-3 menurutmu?", depth: 1 },
    { id: "fn-45", categoryId: "fun", text: "Kalau hidupmu adalah video game, apa cheat code-nya?", depth: 1 },
    { id: "fn-46", categoryId: "fun", text: "Apa rasa es krim yang menurutmu harusnya ada tapi belum ada?", depth: 1 },
    { id: "fn-47", categoryId: "fun", text: "Kalau kamu bisa bicara dengan satu benda di kamarmu, pilih mana?", depth: 1 },
    { id: "fn-48", categoryId: "fun", text: "Apa nama band yang cocok buat kita?", depth: 1 },
    { id: "fn-49", categoryId: "fun", text: "Kalau kamu jadi hantu, siapa orang pertama yang bakal kamu gentayangi?", depth: 1 },
    { id: "fn-50", categoryId: "fun", text: "Apa kombinasi makanan aneh yang enak menurutmu?", depth: 1 },
    { id: "fn-51", categoryId: "fun", text: "Kalau kamu bisa menghapus satu hari dalam seminggu, hari apa yang kamu hapus?", depth: 1 },
    { id: "fn-52", categoryId: "fun", text: "Apa hal paling gila yang pernah kamu lakukan demi diskon?", depth: 1 },
    { id: "fn-53", categoryId: "fun", text: "Kalau kamu jadi presiden, libur nasional apa yang bakal kamu tambah?", depth: 1 },
    { id: "fn-54", categoryId: "fun", text: "Apa lagu dangdut yang paling pas buat suasana hatimu sekarang?", depth: 1 },
    { id: "fn-55", categoryId: "fun", text: "Kalau ada zombie apocalypse, siapa temanmu yang bakal mati duluan?", depth: 1 },
    { id: "fn-56", categoryId: "fun", text: "Apa nama wifi paling kreatif yang pernah kamu liat?", depth: 1 },
    { id: "fn-57", categoryId: "fun", text: "Kalau kamu bisa jadi karakter fiksi jahat, mau jadi siapa?", depth: 1 },
    { id: "fn-58", categoryId: "fun", text: "Apa hal yang kamu harap orang lain tidak melihatmu melakukannya?", depth: 1 },
    { id: "fn-59", categoryId: "fun", text: "Kalau kamu bisa menukar suaramu dengan suara artis, siapa yang kamu pilih?", depth: 1 },
    { id: "fn-60", categoryId: "fun", text: "Apa pertanyaan paling bodoh yang pernah kamu tanyakan ke Google?", depth: 1 },
    { id: "fn-61", categoryId: "fun", text: "Kalau kamu harus memakai satu warna baju seumur hidup, warna apa?", depth: 1 },
    { id: "fn-62", categoryId: "fun", text: "Apa hal yang menurutmu ilegal padahal sebenernya legal?", depth: 1 },
    { id: "fn-63", categoryId: "fun", text: "Kalau kamu bisa punya tombol 'undo' di kehidupan nyata, kapan kamu bakal pake?", depth: 1 },
    { id: "fn-64", categoryId: "fun", text: "Apa tarian andalanmu kalau lagi sendirian?", depth: 1 },
    { id: "fn-65", categoryId: "fun", text: "Kalau kamu bisa makan malam sama 3 orang terkenal (hidup/mati), siapa aja?", depth: 1 },
    { id: "fn-66", categoryId: "fun", text: "Apa hal paling tidak berguna yang kamu hafal?", depth: 1 },
    { id: "fn-67", categoryId: "fun", text: "Kalau kamu jadi superhero, apa kelemahan konyolmu?", depth: 1 },
    { id: "fn-68", categoryId: "fun", text: "Apa hal yang bikin kamu langsung swipe left di aplikasi dating?", depth: 1 },
    { id: "fn-69", categoryId: "fun", text: "Kalau kamu bisa punya peliharaan dinosaurus, jenis apa?", depth: 1 },
    { id: "fn-70", categoryId: "fun", text: "Apa konspirasi teori buatanmu sendiri?", depth: 1 },
    { id: "fn-71", categoryId: "fun", text: "Kalau kamu bisa ganti suara klakson mobilmu, mau diganti suara apa?", depth: 1 },
    { id: "fn-72", categoryId: "fun", text: "Apa hal yang paling sering kamu hilangkan?", depth: 1 },
    { id: "fn-73", categoryId: "fun", text: "Kalau kamu bisa masuk ke dalam lukisan, lukisan mana?", depth: 1 },
    { id: "fn-74", categoryId: "fun", text: "Apa hal yang paling bikin kamu ilfeel saat makan?", depth: 1 },
    { id: "fn-75", categoryId: "fun", text: "Kalau kamu bisa jadi influencer, produk apa yang nggak mau kamu endorse?", depth: 1 },
    { id: "fn-76", categoryId: "fun", text: "Apa hal yang menurutmu overrated banget?", depth: 1 },
    { id: "fn-77", categoryId: "fun", text: "Kalau kamu bisa punya pintu ajaib doraemon, mau tembus ke mana sekarang?", depth: 1 },
    { id: "fn-78", categoryId: "fun", text: "Apa hal yang paling kamu takuti dari teknologi masa depan?", depth: 1 },
    { id: "fn-79", categoryId: "fun", text: "Kalau kamu bisa merubah satu hukum fisika, apa yang kamu ubah?", depth: 1 },
    { id: "fn-80", categoryId: "fun", text: "Apa mimpi teraneh yang pernah kamu ingat?", depth: 1 },
    { id: "fn-81", categoryId: "fun", text: "Kalau kamu bisa jadi atlet olimpiade, cabang olahraga apa?", depth: 1 },
    { id: "fn-82", categoryId: "fun", text: "Apa hal yang paling sering kamu bohongi di CV?", depth: 1 },
    { id: "fn-83", categoryId: "fun", text: "Kalau kamu bisa hidup di film Disney, mau jadi siapa?", depth: 1 },
    { id: "fn-84", categoryId: "fun", text: "Apa hal yang paling kamu benci dari hari Senin?", depth: 1 },
    { id: "fn-85", categoryId: "fun", text: "Kalau kamu bisa punya kembaran, apa yang bakal kalian lakuin?", depth: 1 },
    { id: "fn-86", categoryId: "fun", text: "Apa hal yang paling kamu takuti kalau jadi terkenal?", depth: 1 },
    { id: "fn-87", categoryId: "fun", text: "Kalau kamu bisa ganti mata uang jadi benda lain, benda apa?", depth: 1 },
    { id: "fn-88", categoryId: "fun", text: "Apa hal yang paling sering kamu komplain?", depth: 1 },
    { id: "fn-89", categoryId: "fun", text: "Kalau kamu bisa punya robot yang mirip kamu, dia bakal kamu suruh ngapain?", depth: 1 },
    { id: "fn-90", categoryId: "fun", text: "Apa hal yang paling kamu rindukan dari zaman purba (padahal nggak ngalamin)?", depth: 1 },
    { id: "fn-91", categoryId: "fun", text: "Kalau kamu bisa jadi bajak laut, apa nama kapalmu?", depth: 1 },
    { id: "fn-92", categoryId: "fun", text: "Apa hal yang paling kamu benci dari transportasi umum?", depth: 1 },
    { id: "fn-93", categoryId: "fun", text: "Kalau kamu bisa punya tato yang bisa gerak, gambar apa?", depth: 1 },
    { id: "fn-94", categoryId: "fun", text: "Apa hal yang paling kamu takuti kalau jadi tua?", depth: 1 },
    { id: "fn-95", categoryId: "fun", text: "Kalau kamu bisa punya saku ajaib, apa barang pertama yang kamu keluarin?", depth: 1 },
    { id: "fn-96", categoryId: "fun", text: "Apa hal yang paling kamu benci dari menjadi dewasa?", depth: 1 },
    { id: "fn-97", categoryId: "fun", text: "Kalau kamu bisa jadi karakter game, apa jurus andalanmu?", depth: 1 },
    { id: "fn-98", categoryId: "fun", text: "Apa hal yang paling kamu takuti dari pernikahan?", depth: 1 },
    { id: "fn-99", categoryId: "fun", text: "Kalau kamu bisa punya rumah di planet lain, planet mana?", depth: 1 },
    { id: "fn-100", categoryId: "fun", text: "Apa hal yang paling kamu benci dari musim hujan?", depth: 1 },
    { id: "fn-101", categoryId: "fun", text: "Kalau kamu bisa jadi detektif, kasus apa yang mau kamu pecahkan?", depth: 1 },
    { id: "fn-102", categoryId: "fun", text: "Apa hal yang paling kamu takuti dari dokter gigi?", depth: 1 },
    { id: "fn-103", categoryId: "fun", text: "Kalau kamu bisa punya kekuatan untuk menghentikan waktu, apa yang bakal kamu lakuin?", depth: 1 },
    { id: "fn-104", categoryId: "fun", text: "Apa hal yang paling kamu benci dari menunggu?", depth: 1 },
    { id: "fn-105", categoryId: "fun", text: "Kalau kamu bisa jadi raja/ratu, apa perintah pertamamu?", depth: 1 },
    { id: "fn-106", categoryId: "fun", text: "Kalau kamu jadi presiden, lagu apa yang wajib diputer sebelum pidato kenegaraan?", depth: 1 },
    { id: "fn-107", categoryId: "fun", text: "Kalau nyamuk menghisap lemak bukan darah, apa yang bakal kamu lakuin?", depth: 1, followUps: ["Buka jendela lebar-lebar?"] },
    { id: "fn-108", categoryId: "fun", text: "Pilih: Punya tombol 'Mute' buat orang cerewet atau tombol 'Fast Forward' buat momen ngebosenin?", depth: 1 },
    { id: "fn-109", categoryId: "fun", text: "Kalau kamu wajib ganti nama jadi nama makanan Indonesia, mau dipanggil apa?", depth: 1 },
    { id: "fn-110", categoryId: "fun", text: "Apa konspirasi tentang dirimu sendiri yang mungkin dipercaya orang lain?", depth: 1 },
    { id: "fn-111", categoryId: "fun", text: "Kalau alien mendarat dan minta dibawa ke 'pemimpin' kamu, kamu bawa ke siapa?", depth: 1, followUps: ["Ibumu? Pak RT? Atau Kucingmu?"] },
    { id: "fn-112", categoryId: "fun", text: "Satu benda di kamarmu yang kalau dia bisa ngomong, kamu bakal dalam masalah besar?", depth: 1 },
    { id: "fn-113", categoryId: "fun", text: "Kalau reinkarnasi itu nyata, di kehidupan selanjutnya kamu mau jadi benda apa?", depth: 1 },
    { id: "fn-114", categoryId: "fun", text: "Apa judul skripsi/tugas akhir yang cocok buat menceritakan kisah cintamu?", depth: 1 },
    { id: "fn-115", categoryId: "fun", text: "Kalau bisa download kemampuan kayak di film Matrix, kemampuan receh apa yang kamu mau?", depth: 1, followUps: ["Jago kupas salak? Jago nawar di pasar?"] },
    { id: "fn-116", categoryId: "fun", text: "Kalau kamu jadi hantu, mau jadi hantu jenis apa dan bakal gentayangan di mana?", depth: 1 },
    { id: "fn-117", categoryId: "fun", text: "Sebutkan satu teori konspirasi yang diem-diem kamu percaya!", depth: 1 },
    { id: "fn-118", categoryId: "fun", text: "Kalau disuruh makan makanan kucing demi uang 5 juta, gas nggak?", depth: 1 },
    { id: "fn-119", categoryId: "fun", text: "Apa search history Google terakhirmu yang paling memalukan kalau kebaca orang?", depth: 1 },
    { id: "fn-120", categoryId: "fun", text: "Kalau binatang bisa ngomong, binatang apa yang menurutmu paling kasar omongannya?", depth: 1, followUps: ["Kucing? Angsa?"] },
    { id: "fn-121", categoryId: "fun", text: "Pilih: Napas bau naga seumur hidup atau ketek bau bawang seumur hidup?", depth: 1 },
    { id: "fn-122", categoryId: "fun", text: "Kalau hidupmu adalah Sitkom (Komedi), siapa yang bakal mainin 'laugh track' (suara ketawa)?", depth: 1 },
    { id: "fn-123", categoryId: "fun", text: "Apa hal ilegal yang ingin kamu lakuin kalau nggak ada hukum?", depth: 1 },
    { id: "fn-124", categoryId: "fun", text: "Kalau kamu kejebak di lift sama Presiden, apa kalimat pertama yang kamu ucapin?", depth: 1 },
    { id: "fn-125", categoryId: "fun", text: "Sebutkan skill 'tidak berguna' yang kamu banggakan!", depth: 1, followUps: ["Bisa melipat lidah? Bisa gerakin kuping?"] },

    // ============================
    // WILD CARD (Playful Nudges)
    // ============================
    { id: "wc-1", categoryId: "wildcard", type: "wildcard", intensity: 1, text: "Berikan pujian tulus kepada orang di sebelah kananmu.", depth: 1 },
    { id: "wc-2", categoryId: "wildcard", type: "wildcard", intensity: 2, text: "Tanyakan satu hal yang paling membuatmu penasaran tentang lawan bicaramu saat ini.", depth: 2 },
    { id: "wc-3", categoryId: "wildcard", type: "wildcard", intensity: 1, text: "Ganti posisi duduk dengan orang yang paling jauh darimu.", depth: 1 },
    { id: "wc-4", categoryId: "wildcard", type: "wildcard", intensity: 1, text: "Berikan satu senyuman terbaikmu ke semua orang sebelum lanjut.", depth: 1 },
    { id: "wc-5", categoryId: "wildcard", type: "wildcard", intensity: 3, text: "Wildcard: Tatap mata lawan bicaramu selama 10 detik tanpa bicara.", depth: 3 },
    { id: "wc-6", categoryId: "wildcard", type: "wildcard", intensity: 1, text: "Semua orang harus melakukan peregangan kecil selama 10 detik. Tarik napas...", depth: 1 },
    { id: "wc-7", categoryId: "wildcard", type: "wildcard", intensity: 2, text: "Coba tebak satu lagu favorit orang di depanmu. Kalau salah, dia yang kasih tahu.", depth: 2 },
    { id: "wc-8", categoryId: "wildcard", type: "wildcard", intensity: 1, text: "Gunakan logat daerah yang paling kamu tahu untuk menjawab pertanyaan berikutnya.", depth: 1 },
    { id: "wc-9", categoryId: "wildcard", type: "wildcard", intensity: 2, text: "Sebutkan satu hal kecil yang kamu syukuri dari orang yang paling terakhir berbicara.", depth: 2 },
    { id: "wc-10", categoryId: "wildcard", type: "wildcard", intensity: 1, text: "Lakukan toast (tos) kecil dengan orang-orang di dekatmu.", depth: 1 },
    { id: "wc-11", categoryId: "wildcard", type: "wildcard", intensity: 3, text: "Tunjukkan satu foto random di galeri HP-mu yang punya cerita menyenangkan.", depth: 3 },
    { id: "wc-12", categoryId: "wildcard", type: "wildcard", intensity: 1, text: "Sebutkan satu kata yang menggambarkan suasana momen ini.", depth: 1 },
    { id: "wc-13", categoryId: "wildcard", type: "wildcard", intensity: 2, text: "Pilih satu orang untuk memberikan 'fakta unik' tentang dirinya yang belum kita tahu.", depth: 2 },
    { id: "wc-14", categoryId: "wildcard", type: "wildcard", intensity: 1, text: "Berikan 'high five' virtual ke semua orang yang ada di sini.", depth: 1 },
    { id: "wc-15", categoryId: "wildcard", type: "wildcard", intensity: 2, text: "Coba deskripsikan orang di kirimu menggunakan hanya 3 kata sifat positif.", depth: 2 },
    { id: "wc-16", categoryId: "wildcard", type: "wildcard", intensity: 1, text: "Semua orang boleh memejamkan mata dan menarik napas dalam selama 5 detik.", depth: 1 },
    { id: "wc-17", categoryId: "wildcard", type: "wildcard", intensity: 3, text: "Tantang satu orang untuk melakukan suit (batu-gunting-kertas). Yang menang boleh tanya 1 hal bebas.", depth: 3 },
    { id: "wc-18", categoryId: "wildcard", type: "wildcard", intensity: 1, text: "Ucapkan 'Terima kasih sudah dengerin' ke orang yang terakhir berbicara.", depth: 1 },
    { id: "wc-19", categoryId: "wildcard", type: "wildcard", intensity: 2, text: "Tampilkan satu ekspresi wajah paling 'santai' yang kamu punya.", depth: 2 },
    { id: "wc-20", categoryId: "wildcard", type: "wildcard", intensity: 1, text: "Sebutkan satu emoji yang paling mewakili perasaanmu saat ini.", depth: 1 },
    { id: "wc-21", categoryId: "wildcard", type: "wildcard", intensity: 2, text: "Gunakan kata 'Anu' setidaknya dua kali dalam jawaban pertanyaan berikutnya.", depth: 1 },
    { id: "wc-22", categoryId: "wildcard", type: "wildcard", intensity: 3, text: "Mintalah satu orang memberikan rekomendasi hal seru (film/buku/makanan) untukmu.", depth: 2 },
    { id: "wc-23", categoryId: "wildcard", type: "wildcard", intensity: 1, text: "Tunjukkan jempolmu (thumb's up) kepada siapa pun yang menurutmu ceritanya seru tadi.", depth: 1 },
    { id: "wc-24", categoryId: "wildcard", type: "wildcard", intensity: 2, text: "Tebal atau Tipis? Tanyakan preferensi satu hal random (misal: kerupuk, selimut, atau casing HP) ke grup.", depth: 1 },
    { id: "wc-25", categoryId: "wildcard", type: "wildcard", intensity: 3, text: "Saling lempar pujian secara estafet sampai semua orang dapat giliran.", depth: 3 },
];

// ============================
// CLOSING MESSAGES (Emotional Soft Landing)
// ============================
export const CLOSING_MESSAGES = [
    "Terima kasih sudah berbagi cerita hari ini. Hal-hal kecil kayak gini yang bikin kita makin dekat.",
    "Obrolan hari ini seru banget. Kadang kita lupa betapa pentingnya sekadar duduk dan ngobrol.",
    "Semoga ada satu atau dua cerita dari hari ini yang bikin kamu senyum pas mau tidur nanti.",
    "Nggak ada jawaban benar atau salah, yang ada cuma cerita kita. Makasih udah jadi diri sendiri.",
    "Capek ya? Istirahat yang cukup. Besok kita mulai hari baru dengan semangat baru.",
    "Senang rasanya bisa mengenal sisi lain dari kalian semua. Sampai ketemu di obrolan berikutnya!",
    "Dunia di luar sana mungkin berisik, tapi semoga momen ini ngasih sedikit ketenangan.",
    "Teman ngobrol itu investasi terbaik. Jaga terus koneksi ini ya.",
    "Udah, jangan dipikirin lagi jawaban tadi. Yang penting kita udah ketawa bareng.",
    "Pulang dengan hati ringan ya. Kalian semua keren banget hari ini.",
    "Kadang yang kita butuhkan cuma telinga yang mendengar dan hati yang mengerti. Thanks for today.",
    "Jangan lupa minum air putih dan istirahat. Kesehatanmu lebih penting dari apapun.",
    "Setiap orang punya cerita. Makasih udah ngasih kepercayaan buat dengerin ceritamu.",
    "Kalau besok berat, inget aja kita pernah ketawa lepas gara-gara pertanyaan konyol tadi.",
    "Stay safe, stay sane, and stay kind. Sampai jumpa lagi!",
    "Terima kasih sudah meluangkan waktu. Nggak harus lama, yang penting rasanya nyata.",
    "Hari ini mungkin biasa saja, tapi obrolannya nggak. Semoga terasa sampai nanti.",
    "Ada hal-hal yang nggak perlu disimpulkan. Cukup dirasain sebentar, lalu disimpan.",
    "Semoga setelah ini, suasananya jadi sedikit lebih hangat dari sebelumnya.",
    "Nggak semua momen harus bermakna besar. Yang kecil-kecil juga layak dirayakan.",
    "Kalau ada yang kepikiran setelah ini, berarti obrolannya kena di hati.",
    "Terima kasih sudah hadir sepenuhnya, walau cuma sebentar.",
    "Kadang ngobrol ringan justru yang paling kita butuhkan hari ini.",
    "Semoga pulangnya nggak cuma bawa HP, tapi juga perasaan yang lebih ringan.",
    "Momen kayak gini jarang terasa penting sekarang, tapi sering diingat nanti.",
    "Nggak apa-apa kalau masih kepikiran satu dua jawaban. Itu bagian dari proses.",
    "Terima kasih sudah bikin sesi ini hidup dengan caramu sendiri.",
    "Kalau hari ini melelahkan, semoga obrolan tadi jadi jeda yang menyenangkan.",
    "Semoga setelah ini, kamu merasa sedikit lebih ditemani.",
    "Nggak perlu buru-buru. Semua hal baik memang datang pelan-pelan.",
    "Terima kasih sudah ikut meramaikan ruang kecil ini.",
    "Mungkin sederhana, tapi momen ini tetap berarti.",
    "Kalau ada yang bikin senyum kecil barusan, itu sudah cukup.",
    "Terima kasih sudah berbagi ruang, waktu, dan cerita.",
    "Sampai jumpa lagi, di obrolan yang nggak perlu dipaksakan."
];
